
/* ---------------- ANAK KANDANG (mobile-first) ---------------- */
function akShell(content,active){const u=state.user;return `<div class="mob">
 <div class="mob-head"><img src="/img/logo-mark.png" alt="" style="width:40px;height:auto"><div style="flex:1"><b style="display:block;font-size:15px">AR-FARM</b><small style="color:var(--sage)">${barnName(u.barn)} · ${u.name.split(' ')[0]}</small></div><button class="iconbtn" data-act="logout" title="Keluar">${ic('out')}</button></div>
 <div class="demo-band">${DB.farm.name} · ${fmtLong(DEMO_TODAY)} · Hari ke-${calc.day()}</div>
 <div class="mob-body">${content}</div>
 <nav class="mob-nav">${[['ak-home','Home','home'],['ak-input','Input','plus'],['ak-kandang','Kandang','barn'],['ak-riwayat','Riwayat','history']].map(([p,l,i])=>`<button class="${active===p?'active':''}" data-act="go" data-page="${p}">${ic(i,22)}<span>${l}</span></button>`).join('')}</nav></div>`;}
function akHome(){const u=state.user;const b=u.barn;const today=calc.day();const fedToday=DB.feedRecords.filter(r=>r.barn===b&&dayOf(r.date)===today);const mortToday=DB.mortality.filter(m=>m.barn===b&&dayOf(m.date)===today);const condToday=DB.barnCond.find(c=>c.barn===b&&dayOf(c.date)===today);const weighed=DB.weights.some(w=>w.barn===b&&dayOf(w.date)===today);
 return `<div class="hero" style="min-height:130px;padding:18px"><img class="art" src="/img/logo-mark.png" alt="" style="opacity:.18;width:170px"><small style="color:var(--sage);font-weight:700">Selamat pagi, ${u.name.split(' ')[0]} 👋</small><h1 style="font-size:24px">${barnName(b)}</h1><div class="meta"><span><b class="num">${num(calc.population(b))}</b> ekor</span><span>Hari ke-<b>${today}</b></span></div></div>
 <div class="card"><div class="card-h"><h3>Tugas Hari Ini</h3><span class="sub">${fmtDate(DEMO_TODAY)}</span></div><div style="display:flex;flex-direction:column;gap:8px">${[['Input pakan',fedToday.length>0,fedToday.length?num(fedToday.reduce((s,r)=>s+calc.feedVal(r),0))+' kg tercatat':'Belum diinput','ak-pakan'],['Cek & catat kematian',mortToday.length>0||true,mortToday.length?mortToday.reduce((s,m)=>s+m.qty,0)+' ekor':'0 ekor (tidak ada)','ak-mati'],['Kondisi kandang',!!condToday,condToday?'Sudah diisi '+fmtDT(condToday.date).slice(-5):'Belum diisi','ak-kondisi'],['Timbang sampel',weighed,weighed?'Sudah':'Jadwal berikutnya H35','ak-timbang']].map(([t,ok,s,p])=>`<button class="hist" data-act="go" data-page="${p}" style="width:100%;text-align:left;color:inherit;font:inherit;cursor:pointer"><div class="ic" style="color:${ok?'#8FD9AE':'var(--warn)'}">${ic(ok?'check':'clock',18)}</div><div><b>${t}</b><small>${s}</small></div><span class="st">${ok?badge('ok','SELESAI'):badge('warn','BELUM')}</span></button>`).join('')}</div></div>
 <div class="tile-grid"><button class="tile" data-act="go" data-page="ak-pakan"><span class="ic">${ic('feed',20)}</span>Input Pakan</button><button class="tile red" data-act="go" data-page="ak-mati"><span class="ic">${ic('skull',20)}</span>Input Kematian</button><button class="tile gold" data-act="go" data-page="ak-timbang"><span class="ic">${ic('scale',20)}</span>Timbang</button><button class="tile" data-act="go" data-page="ak-kondisi"><span class="ic">${ic('barn',20)}</span>Kondisi Kandang</button></div>
 <div class="alert info">${ic('lock',16)}<div><b>Data terkunci setelah disimpan</b>Salah input? Ajukan koreksi di menu Riwayat. Manager akan menyetujui.</div></div>`;}
function akInputMenu(){return `<h2 style="font-size:20px">Mau input apa?</h2><div class="tile-grid"><button class="tile" data-act="go" data-page="ak-pakan"><span class="ic">${ic('feed',20)}</span>Input Pakan</button><button class="tile red" data-act="go" data-page="ak-mati"><span class="ic">${ic('skull',20)}</span>Input Kematian</button><button class="tile gold" data-act="go" data-page="ak-timbang"><span class="ic">${ic('scale',20)}</span>Timbang</button><button class="tile" data-act="go" data-page="ak-kondisi"><span class="ic">${ic('barn',20)}</span>Kondisi Kandang</button><button class="tile" data-act="go" data-page="ak-sehat"><span class="ic">${ic('heart',20)}</span>Kesehatan</button></div>`;}
function akSuccess(){const s=state.akSuccess;return `<div class="success-screen"><div class="chk">${ic('check',40)}</div><h2>Data berhasil dicatat.</h2><p style="color:var(--muted)">${s.text}</p><div class="kv" style="text-align:left;background:rgba(255,255,255,.05);padding:12px;border-radius:12px"><span>Waktu</span><b class="num">${fmtDT(s.date)}</b><span>Oleh</span><b>${state.user.name}</b><span>Bukti</span><b>${s.photo||'—'}</b><span>Lokasi</span><b>${MASTER.gpsDicatat?'tercatat':'—'}</b><span>Status</span><b>${stBadge('RECORDED')}</b></div><button class="btn primary lg" data-act="go" data-page="ak-home">Kembali ke Home</button><button class="btn lg" data-act="go" data-page="${s.again}">Input lagi</button></div>`;}
function photoField(id){return `<div class="f"><label>Foto bukti ${MASTER.fotoWajib?'<span style="color:#F29390">*wajib</span>':''}</label><label class="upload" id="up-${id}" for="file-${id}">${ic('camera',22)}<div style="margin-top:6px;font-weight:700">AMBIL FOTO</div><small>Kamera terbuka otomatis di HP</small></label><input type="file" accept="image/*" capture="environment" id="file-${id}" name="photo" hidden data-act="photo" data-target="up-${id}"></div>`;}
function akPakan(){const u=state.user;return `<h2 style="font-size:20px">Input Pakan</h2><form class="form" data-act="ak-save-feed"><div class="f"><label>Berapa kg?</label><input class="big-in num" type="number" name="kg" inputmode="decimal" placeholder="0" min="1" max="500" required id="ak-kg"></div><div class="f"><label>Kandang</label><div class="choice">${DB.barns.filter(b=>b.id!=='C').map(b=>`<button type="button" class="${(state.filters.akBarn||u.barn)===b.id?'active':''}" data-act="ak-barn" data-v="${b.id}" ${u.barn!==b.id?'disabled title="Bukan kandang Anda"':''}>${b.name}</button>`).join('')}</div></div><div class="f"><label>Jenis pakan</label><select name="jenis"><option>Grower (H15–H35)</option><option>Starter</option><option>Finisher</option></select></div>${photoField('feed')}<div class="kv" style="font-size:12px"><span>Tanggal</span><b>${fmtDate(DEMO_TODAY)} (otomatis)</b><span>Jam</span><b>${DEMO_TODAY.toTimeString().slice(0,5)} (otomatis)</b><span>Populasi</span><b class="num">${num(calc.population(u.barn))} ekor</b></div><button class="btn primary lg" type="submit">SIMPAN</button></form>`;}
function akMati(){const u=state.user;const q=state.filters.akQty||0;return `<h2 style="font-size:20px">Input Kematian</h2><form class="form" data-act="ak-save-mort"><div class="f"><label>Berapa ekor mati?</label><div class="stepper"><button type="button" data-act="ak-step" data-v="-1">−</button><input class="big-in num" type="number" name="qty" value="${q}" min="0" max="50" id="ak-qty" required><button type="button" data-act="ak-step" data-v="1">+</button></div></div><div class="f"><label>Kandang</label><div class="choice">${DB.barns.filter(b=>b.id!=='C').map(b=>`<button type="button" class="${u.barn===b.id?'active':''}" ${u.barn!==b.id?'disabled':''}>${b.name}</button>`).join('')}</div></div><div class="f"><label>Penyebab</label><select name="cause"><option>Belum diketahui</option><option>Lemah / kerdil</option><option>Terinjak</option><option>Sakit (diare)</option><option>Sakit (pernapasan)</option><option>Kaki lumpuh</option><option>Predator</option><option>Lainnya</option></select></div><div class="f"><label>Catatan (opsional)</label><textarea name="note" rows="2" placeholder="Contoh: ditemukan pagi di sudut timur"></textarea></div>${photoField('mort')}<button class="btn primary lg" type="submit">SIMPAN</button></form>`;}
function akTimbang(){const u=state.user;return `<h2 style="font-size:20px">Timbang Sampel</h2><form class="form" data-act="ak-save-weight"><div class="f-row"><div class="f"><label>Jumlah sampel (ekor)</label><input class="big-in num" style="font-size:28px" type="number" name="n" value="20" min="5" max="50" required id="ak-n" data-act="calc-avg"></div><div class="f"><label>Total berat (kg)</label><input class="big-in num" style="font-size:28px" type="number" step="0.1" name="total" placeholder="0,0" required id="ak-total" data-act="calc-avg"></div></div><div class="alert info" id="avg-box">${ic('scale',16)}<div><b>Rata-rata: <span id="avg-val">—</span></b><small>Target hari ke-${calc.day()}: ${num(calc.target(calc.day()),2)} kg/ekor</small></div></div><div class="f"><label>Kandang</label><div class="choice"><button type="button" class="active" disabled>${barnName(u.barn)}</button></div></div>${photoField('weigh')}<button class="btn primary lg" type="submit">SIMPAN</button></form>`;}
function akKondisi(){const u=state.user;const opt=(n,arr,def)=>`<div class="f"><label>${n}</label><div class="choice">${arr.map(a=>`<button type="button" class="ch-${n.replace(/\s/g,'')} ${a===def?'active':''}" data-act="choice" data-group="${n.replace(/\s/g,'')}" data-v="${a}">${a}</button>`).join('')}</div><input type="hidden" name="${n.replace(/\s/g,'')}" value="${def}"></div>`;
 return `<h2 style="font-size:20px">Kondisi Kandang</h2><form class="form" data-act="ak-save-cond"><div class="f-row"><div class="f"><label>Suhu (°C)</label><input class="big-in" style="font-size:28px" type="number" name="temp" value="28" required></div><div class="f"><label>Kelembapan (%)</label><input class="big-in" style="font-size:28px" type="number" name="hum" value="75" required></div></div>${opt('Sekam',['Kering','Agak lembab','Basah'],'Kering')}${opt('Air minum',['Lancar','Tersendat','Kosong'],'Lancar')}${opt('Perilaku bebek',['Aktif','Lesu','Menggerombol'],'Aktif')}<div class="f"><label>Catatan</label><textarea name="note" rows="2" placeholder="Opsional"></textarea></div>${photoField('cond')}<button class="btn primary lg" type="submit">SIMPAN</button></form>`;}
function akSehat(){return `<h2 style="font-size:20px">Input Kesehatan</h2><form class="form" data-act="ak-save-health"><div class="f"><label>Jenis</label><select name="type"><option>Vitamin</option><option>Pengobatan</option><option>Observasi</option></select></div><div class="f"><label>Nama / item</label><input name="item" placeholder="Contoh: Vitachick" required></div><div class="f"><label>Dosis</label><input name="dose" placeholder="Contoh: 1 g/L"></div><div class="f"><label>Catatan</label><textarea name="note" rows="2"></textarea></div>${photoField('health')}<button class="btn primary lg" type="submit">SIMPAN</button></form>`;}
function akKandang(){const b=state.user.barn;const cond=DB.barnCond.filter(c=>c.barn===b)[0];return `<h2 style="font-size:20px">${barnName(b)}</h2><div class="grid" style="grid-template-columns:1fr 1fr">${kpi('Populasi',num(calc.population(b)),'ekor','','','duck')}${kpi('Mati (siklus)',calc.mortTotal(b),'ekor','','','skull','red')}${kpi('Bobot',num(calc.avgWeight(b),2),'kg',`Target ${num(calc.target(calc.day()),2)}`,'','scale')}${kpi('Pakan hari ini',num(DB.feedRecords.filter(r=>r.barn===b&&dayOf(r.date)===calc.day()).reduce((s,r)=>s+calc.feedVal(r),0)),'kg','','','feed')}</div>${cond?`<div class="card"><div class="card-h"><h3>Kondisi terakhir</h3><span class="sub">${fmtDT(cond.date)}</span></div><div class="kv"><span>Suhu</span><b>${cond.temp}°C</b><span>Kelembapan</span><b>${cond.hum}%</b><span>Sekam</span><b>${cond.litter}</b><span>Air</span><b>${cond.water}</b></div></div>`:''}<div class="card"><div class="card-h"><h3>Jadwal Minggu Ini</h3></div><div class="timeline"><div class="tl done"><div class="t">H28</div><div class="b">Vitamin + elektrolit</div></div><div class="tl now"><div class="t">H32 · Hari ini</div><div class="b">Timbang sampel</div></div><div class="tl todo"><div class="t">H35</div><div class="b">Vitamin · Timbang</div></div><div class="tl todo"><div class="t">H36</div><div class="b">Ganti pakan finisher</div></div></div></div><div class="alert info">${ic('lock',16)}<div><b>Menu keuangan tidak tersedia</b>Harga, omzet, dan laba hanya untuk Owner.</div></div>`;}
function akRiwayat(){const u=state.user;const items=[...DB.feedRecords.filter(r=>r.user===u.id).map(r=>({date:r.date,t:'Pakan',v:calc.feedVal(r)+' kg',ic:'feed',id:r.id,type:'FEED',corr:DB.corrections.find(c=>c.recordId===r.id&&c.status==='PENDING'),locked:r.locked,vers:r.versions.length})),...DB.mortality.filter(m=>m.user===u.id).map(m=>({date:m.date,t:'Kematian',v:m.qty+' ekor · '+m.cause,ic:'skull',id:m.id,type:'MORT',locked:m.locked})),...DB.weights.filter(w=>w.user===u.id).map(w=>({date:w.date,t:'Timbang',v:num(w.avg,2)+' kg ('+w.n+' ekor)',ic:'scale',id:w.id,type:'WEIGHT',locked:w.locked})),...DB.barnCond.filter(c=>c.user===u.id).map(c=>({date:c.date,t:'Kondisi kandang',v:c.temp+'°C · '+c.litter,ic:'barn',id:c.id,type:'COND',locked:true}))].sort((a,b)=>b.date-a.date).slice(0,20);
 return `<h2 style="font-size:20px">Riwayat Input Saya</h2><p style="color:var(--muted);font-size:13px">Hanya input Anda sendiri yang ditampilkan.</p>${items.map(i=>`<div class="hist"><div class="ic">${ic(i.ic,18)}</div><div style="min-width:0"><b>${i.t} · ${i.v}</b><small>${fmtDT(i.date)}${i.vers?' · '+badge('info','DIKOREKSI'):''}</small></div><span class="st">${i.corr?badge('pending','KOREKSI MENUNGGU'):i.type!=='COND'?`<button class="btn ghost sm" data-act="modal" data-m="correction" data-type="${i.type}" data-id="${i.id}">Ajukan koreksi</button>`:badge('neutral','TERKUNCI')}</span></div>`).join('')}`;}

/* ---------------- MODALS ---------------- */
const modalWrap=(title,body,foot,cls='modal')=>`<div class="modal-bg" data-act="modal-close-bg"><div class="${cls}" data-stop><div class="mh"><h3>${title}</h3><button class="iconbtn" style="width:32px;height:32px" data-act="modal-close">${ic('x',16)}</button></div><div class="mb">${body}</div>${foot?`<div class="mf">${foot}</div>`:''}</div></div>`;
function openModal(m,opts={}){state.modal={m,opts};renderLayer();}
function closeModal(){state.modal=null;renderLayer();}
function renderLayer(){const L=document.getElementById('layer');let html='';if(state.modal)html+=modalHTML(state.modal.m,state.modal.opts);if(state.aiOpen)html+=aiDrawer();L.innerHTML=html;const f=L.querySelector('input:not([type=hidden]),select,textarea');if(f&&state.modal)setTimeout(()=>f.focus(),50);}
function modalHTML(m,o){
 const barnSel=(name='barn')=>`<div class="f"><label>Kandang</label><select name="${name}">${DB.barns.filter(b=>b.id!=='C').map(b=>`<option value="${b.id}">${b.name}</option>`).join('')}</select></div>`;
 if(m==='correction'){const rec=o.type==='FEED'?DB.feedRecords.find(r=>r.id===o.id):o.type==='MORT'?DB.mortality.find(r=>r.id===o.id):DB.weights.find(r=>r.id===o.id);const old=o.type==='FEED'?calc.feedVal(rec)+' kg':o.type==='MORT'?rec.qty+' ekor':rec.total+' kg (total)';const unit=o.type==='FEED'?'kg':o.type==='MORT'?'ekor':'kg';
  return modalWrap('Ajukan Koreksi',`<div class="alert info" style="margin-bottom:12px">${ic('lock',16)}<div><b>Data asli tidak diubah</b>Koreksi membuat versi baru setelah disetujui Owner/Manager. Versi lama tetap tersimpan.</div></div><form class="form" id="corr-form" data-act="submit-correction" data-type="${o.type}" data-id="${o.id}"><div class="f-row"><div class="f"><label>Data lama</label><input class="ro" value="${old}" readonly></div><div class="f"><label>Data baru (${unit})</label><input name="newVal" type="number" step="any" required placeholder="0"></div></div><div class="f"><label>Alasan koreksi</label><select name="reason" required><option value="">Pilih alasan…</option><option>Salah input angka</option><option>Salah kandang</option><option>Input ganda</option><option>Timbangan tidak terkalibrasi</option><option>Lainnya</option></select></div><div class="f"><label>Keterangan</label><textarea name="note" rows="2" placeholder="Jelaskan singkat"></textarea></div>${photoField('corr')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="corr-form">Ajukan Koreksi</button>`);}
 if(m==='order'){return modalWrap('Buat Order Penjualan',`<form class="form" id="order-form" data-act="submit-order"><div class="f"><label>Customer</label><select name="customer" data-act="order-customer">${DB.customers.map(c=>`<option value="${c.id}">${c.name} · ${c.phone}</option>`).join('')}<option value="NEW">+ Customer baru</option></select></div><div class="f-row" id="newcust" hidden><div class="f"><label>Nama customer</label><input name="customerName"></div><div class="f"><label>WhatsApp</label><input name="customerPhone"></div></div><div class="f"><label>Produk</label><select name="product" data-act="order-product">${DB.products.map(p=>`<option value="${p.id}">${p.name} — stok ${num(calc.productStock(p))} · ${rp(MASTER[p.priceKg])}/kg</option>`).join('')}</select></div><div class="f-row"><div class="f"><label>Jumlah (ekor)</label><input name="qty" type="number" min="1" value="10" required id="o-qty" data-act="order-calc"></div><div class="f"><label>Berat total (kg)</label><input name="weight" type="number" step="0.1" placeholder="Isi saat timbang" id="o-w" data-act="order-calc"></div></div><div class="f-row"><div class="f"><label>Harga/kg</label><input name="priceKg" type="number" value="${MASTER[DB.products[0].priceKey]||0}" id="o-p" data-act="order-calc"></div><div class="f"><label>Tanggal kirim/ambil</label><input name="pickup" type="date" value="${new Date(DEMO_TODAY.getTime()+86400000).toISOString().slice(0,10)}"></div></div><div class="kv" style="background:rgba(255,255,255,.05);padding:12px;border-radius:12px"><span>Subtotal</span><b class="num" id="o-sub">—</b><span>Stok setelah order</span><b class="num" id="o-stock">—</b></div><div class="f"><label>Status pembayaran</label><select name="pay"><option value="UNPAID">Belum bayar</option><option value="PAID">Sudah bayar (lunas)</option><option value="DP">DP 50%</option></select></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="order-form">Simpan Order</button>`);}
 if(m==='purchase'){return modalWrap('Pembelian Pakan',`<div class="alert info" style="margin-bottom:12px">${ic('check',16)}<div><b>Butuh persetujuan Owner</b>Pembelian di atas Rp 5.000.000 menunggu approval sebelum menambah stok dan biaya.</div></div><form class="form" id="pur-form" data-act="submit-purchase"><div class="f-row"><div class="f"><label>Jumlah (kg)</label><input name="qty" type="number" value="1000" required></div><div class="f"><label>Harga/kg</label><input name="price" type="number" value="${MASTER.hargaPakanKg}" required></div></div><div class="f"><label>Vendor</label><input name="vendor" value="PT Sinar Pakan Nusantara"></div><div class="f"><label>Nomor bukti / invoice</label><input name="ref" placeholder="INV-…" required></div>${photoField('pur').replace('AMBIL FOTO','FOTO NOTA')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="pur-form">Simpan</button>`);}
 if(m==='expense'){return modalWrap('Catat Biaya',`<form class="form" id="exp-form" data-act="submit-expense"><div class="f-row"><div class="f"><label>Kategori</label><select name="cat">${['Vitamin','Obat','Listrik','Gas','Sekam','Tenaga kerja','Transport','Peralatan','Maintenance','Biaya lain'].map(c=>`<option>${c}</option>`).join('')}</select></div><div class="f"><label>Nominal (Rp)</label><input name="amount" type="number" required placeholder="0"></div></div><div class="f"><label>Vendor</label><input name="vendor" required></div><div class="f"><label>Nomor bukti</label><input name="ref" required></div>${photoField('exp').replace('AMBIL FOTO','FOTO NOTA')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="exp-form">Simpan</button>`);}
 if(m==='opname'){return modalWrap('Stock Opname Pakan',`<form class="form" id="op-form" data-act="submit-opname"><div class="kv" style="margin-bottom:6px"><span>Stok teoritis saat ini</span><b class="num">${num(calc.feedStockTheory())} kg</b></div><div class="f"><label>Stok fisik hasil hitung (kg)</label><input class="big-in" name="physical" type="number" required placeholder="0"></div><div class="f"><label>Catatan</label><input name="note" placeholder="Opsional"></div>${photoField('op').replace('AMBIL FOTO','FOTO TUMPUKAN STOK')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="op-form">Simpan Opname</button>`);}
 if(m==='adjust'){const fd=calc.feedDiff();return modalWrap('Penyesuaian Stok Pakan',`<form class="form" id="adj-form" data-act="submit-adjust"><div class="alert warn" style="margin-bottom:6px">${ic('alert',16)}<div><b>Selisih ${num(fd.diff)} kg</b>Penyesuaian akan mengurangi stok teoritis agar sama dengan fisik. Dicatat sebagai STOCK_ADJUSTMENT dengan alasan.</div></div><div class="f"><label>Jumlah penyesuaian (kg)</label><input name="qty" type="number" value="${-fd.diff}" required></div><div class="f"><label>Alasan (hasil verifikasi)</label><select name="reason" required><option>Susut / tumpah saat penuangan</option><option>Karung tidak penuh dari vendor</option><option>Pemakaian belum tercatat</option><option>Kesalahan hitung opname</option><option>Lainnya</option></select></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="adj-form">Setujui Penyesuaian</button>`);}
 if(m==='mort'){return modalWrap('Catat Kematian',`<form class="form" id="m-form" data-act="submit-mort"><div class="f-row"><div class="f"><label>Jumlah (ekor)</label><input name="qty" type="number" min="1" value="1" required></div>${barnSel()}</div><div class="f"><label>Penyebab</label><select name="cause"><option>Belum diketahui</option><option>Lemah / kerdil</option><option>Terinjak</option><option>Sakit</option><option>Predator</option></select></div>${photoField('m')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="m-form">Simpan</button>`);}
 if(m==='weigh'){return modalWrap('Input Timbang',`<form class="form" id="w-form" data-act="submit-weigh"><div class="f-row"><div class="f"><label>Jumlah sampel</label><input name="n" type="number" value="20" required></div><div class="f"><label>Total berat (kg)</label><input name="total" type="number" step="0.1" required placeholder="0,0"></div></div>${barnSel()}${photoField('w')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="w-form">Simpan</button>`);}
 if(m==='health'){return modalWrap('Catat Tindakan Kesehatan',`<form class="form" id="h-form" data-act="submit-health"><div class="f-row"><div class="f"><label>Jenis</label><select name="type"><option>Vitamin</option><option>Vaksinasi</option><option>Pengobatan</option><option>Observasi</option></select></div><div class="f"><label>Kandang</label><select name="barn"><option value="ALL">Semua</option><option value="A">Kandang A</option><option value="B">Kandang B</option></select></div></div><div class="f"><label>Item</label><input name="item" required></div><div class="f"><label>Dosis</label><input name="dose"></div><div class="f"><label>Catatan</label><textarea name="note" rows="2"></textarea></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="h-form">Simpan</button>`);}
 if(m==='user'){return modalWrap('Tambah Pengguna',`<form class="form" id="u-form" data-act="submit-user"><div class="f"><label>Nama</label><input name="name" required></div><div class="f-row"><div class="f"><label>Role</label><select name="role">${Object.keys(ROLES).map(r=>`<option value="${r}">${ROLES[r].label}</option>`).join('')}</select></div><div class="f"><label>Kandang</label><select name="barn"><option value="">Semua</option><option value="A">Kandang A</option><option value="B">Kandang B</option><option value="C">Kandang C</option></select></div></div><div class="f"><label>Nomor WhatsApp</label><input name="phone" required></div><div class="alert info">${ic('lock',16)}<div><b>Password tidak dibuat di sini</b>Tautan aktivasi sekali pakai dikirim ke WhatsApp pengguna. Password di-hash (argon2) dan tidak pernah ditampilkan.</div></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="u-form">Kirim Undangan</button>`);}
 if(m==='cycle'){return modalWrap('Siklus Baru',`<form class="form" id="c-form" data-act="submit-cycle"><div class="alert warn" style="margin-bottom:6px">${ic('alert',16)}<div><b>Siklus #001 masih aktif</b>Siklus baru hanya bisa dimulai di kandang kosong (Kandang C).</div></div><div class="f-row"><div class="f"><label>Jumlah DOD</label><input name="qty" type="number" value="500"></div><div class="f"><label>Harga DOD</label><input name="price" type="number" value="${MASTER.hargaDOD}" class="ro" readonly></div></div><div class="f"><label>Tanggal DOD masuk</label><input name="date" type="date" value="${new Date(DEMO_TODAY.getTime()+14*86400000).toISOString().slice(0,10)}"></div><div class="f"><label>Kandang</label><select><option>Kandang C</option></select></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" data-act="toast" data-msg="Siklus #002 dijadwalkan (demo)." data-close="1">Buat Siklus</button>`);}
 if(m==='verify'){return modalWrap('Tandai Terverifikasi',`<form class="form" id="v-form" data-act="submit-verify" data-id="${o.id}"><div class="f"><label>Hasil verifikasi</label><textarea name="note" rows="3" required placeholder="Contoh: Dicek langsung, pakan ekstra diberikan karena bebek lebih aktif."></textarea></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn ok" type="submit" form="v-form">Simpan</button>`);}
 if(m==='reject'){return modalWrap('Tolak Permintaan',`<form class="form" id="r-form" data-act="submit-reject" data-id="${o.id}" data-kind="${o.kind}"><div class="f"><label>Alasan penolakan (wajib)</label><textarea name="reason" rows="3" required placeholder="Alasan dikirim ke pengaju dan dicatat di audit trail"></textarea></div></form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn danger" type="submit" form="r-form">Tolak</button>`);}
 if(m==='invin'){return modalWrap('Barang Masuk',`<form class="form" id="i-form" data-act="submit-invin"><div class="f"><label>Item</label><select name="item">${DB.inventory.map(i=>`<option value="${i.id}">${i.name}</option>`).join('')}</select></div><div class="f-row"><div class="f"><label>Jumlah</label><input name="qty" type="number" value="10" required></div><div class="f"><label>Referensi nota</label><input name="ref" required></div></div>${photoField('iv').replace('AMBIL FOTO','FOTO NOTA')}</form>`,`<button class="btn" data-act="modal-close">Batal</button><button class="btn primary" type="submit" form="i-form">Simpan</button>`);}
 if(m==='siteorder'){const p=DB.products.find(x=>x.id===o.product)||DB.products[0];return modalWrap('Pesan Sekarang',`<form class="form" id="s-form" data-act="submit-siteorder"><div class="f-row"><div><label>Nama</label><input name="name" required placeholder="Nama lengkap"></div><div><label>Nomor WhatsApp</label><input name="phone" required placeholder="08xx"></div></div><div><label>Produk</label><select name="product" data-act="site-product">${DB.products.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name} — ${calc.stockStatus(x).t}</option>`).join('')}</select></div><div class="f-row"><div><label>Jumlah (ekor, min. ${p.minOrder})</label><input name="qty" type="number" min="${p.minOrder}" value="${p.minOrder}" required id="s-qty" data-act="site-calc"></div><div><label>Tanggal ambil / kirim</label><input name="pickup" type="date" value="${(p.stockFrom==='population'?dateOfDay(DB.cycle.targetDays+1):new Date(DEMO_TODAY.getTime()+86400000)).toISOString().slice(0,10)}" required></div></div><div><label>Alamat</label><input name="address" placeholder="Alamat pengiriman (kosongkan jika ambil sendiri)"></div><div><label>Catatan</label><textarea name="note" rows="2"></textarea></div><div class="sum"><span>Estimasi berat</span><b id="s-w">${num(p.minOrder*p.avgW,1)} kg</b><span>Harga</span><b>${rp(MASTER[p.priceKg])}/kg</b><span>Estimasi total</span><b id="s-t">${rp(p.minOrder*p.avgW*MASTER[p.priceKg])}</b></div><small style="color:#5F6B66">Total final mengikuti berat timbang saat serah terima.</small></form>`,`<button class="btn-site" style="background:#EEE;color:#333" data-act="modal-close">Batal</button><button class="btn-site wa" type="submit" form="s-form">${ic('wa',16)} Pesan via WhatsApp</button>`,'order-modal');}
 if(m==='sitedone'){const ord=o.order;const text=`Halo AR-FARM, saya ${ord.customerName} ingin memesan ${ord.qty} ekor ${ord.productName} untuk ${fmtDate(toDate(ord.pickup))}. No. order ${ord.id}.`;const url='https://wa.me/'+(DB.waAdmin||'6281211112203')+'?text='+encodeURIComponent(text);
  return modalWrap('Order Diterima',`<div style="text-align:center;padding:10px 0"><div style="width:70px;height:70px;border-radius:50%;background:#DDF0E3;color:#1E6B45;display:grid;place-items:center;margin:0 auto 12px">${ic('check',34)}</div><h3 style="font-size:20px;color:#174A3A">Order ${ord.id} tercatat</h3><p style="color:#5F6B66;margin-top:6px">Order sudah masuk ke dashboard AR-FARM dengan status BARU. Lanjutkan konfirmasi lewat WhatsApp:</p></div><div class="copybox"><code>${esc(text)}</code><button class="btn-site green" style="padding:6px 10px;font-size:12px" data-act="copy" data-text="${esc(text)}">Salin</button></div><a class="btn-site wa" style="width:100%;margin-top:12px" href="${url}" target="_blank" rel="noopener">${ic('wa',16)} Buka WhatsApp 0812-1111-2203</a><small style="display:block;color:#5F6B66;margin-top:8px;text-align:center">Jika tautan tidak terbuka, salin pesan di atas dan kirim manual.</small>`,`<button class="btn-site green" data-act="modal-close">Selesai</button>`,'order-modal');}
 return '';
}

/* ---------------- AI DRAWER ---------------- */
const AI_Q=['Kenapa FCR saya naik?','Berapa pakan yang terpakai minggu ini?','Berapa mortalitas siklus ini?','Berapa modal berjalan?','Berapa estimasi laba?','Apakah bobot bebek sesuai target?','Apakah stok pakan aman?','Berapa harga bebek di pasar?'];
function aiAnswer(q){const s=q.toLowerCase();const fin=can('finance');
 if(/fcr/.test(s)){const f=calc.fcr();if(!f)return'Data belum cukup untuk menghitung FCR.';const fs=calc.fcrSeries().filter(x=>x.fcr);const prev=fs[fs.length-2];return `FCR saat ini ${num(f.fcr,2)} (${num(f.feed)} kg pakan ÷ ${num(f.bio,0)} kg pertambahan biomassa).${prev?` Pada H${prev.day} FCR ${num(prev.fcr,2)}, jadi ${f.fcr>prev.fcr?'naik':'turun'} ${num(Math.abs(f.fcr-prev.fcr),2)}.`:''}\n\nPenyebab yang terlihat di data:\n• Konsumsi pakan hari ini ${num(calc.feedToday())} kg, ${num((calc.feedToday()-calc.feedAvg7())/calc.feedAvg7()*100)}% di atas rata-rata 7 hari.\n• Bobot tertinggal ${num(Math.abs(calc.weightGap()))}% dari target — pakan naik tapi bobot tidak mengikuti.\n• Ada selisih opname ${num(Math.abs(calc.feedDiff().diff))} kg yang belum diverifikasi (bisa jadi pakan tercatat terpakai tapi tidak dimakan).\n\nSaran: verifikasi input pakan 1–2 Okt dan timbang ulang sampel 30 ekor.`;}
 if(/pakan.*(minggu|7 hari)|minggu ini.*pakan/.test(s)){const fb=calc.feedByDay().slice(-7);return `Pakan terpakai 7 hari terakhir: ${num(fb.reduce((a,b)=>a+b,0))} kg (rata-rata ${num(fb.reduce((a,b)=>a+b,0)/7,1)} kg/hari). Rincian per hari: ${fb.join(', ')} kg. Total siklus ${num(calc.feedTotal())} kg.`;}
 if(/mortalitas|kematian|mati/.test(s))return `Mortalitas siklus #001: ${calc.mortTotal()} ekor dari ${DB.cycle.dodQty} DOD (${pct(calc.mortPct())}), masih di bawah target maksimum ${MASTER.targetMortalitasPct}%. Kandang A ${calc.mortTotal('A')} ekor, Kandang B ${calc.mortTotal('B')} ekor. Kematian terakhir ${fmtDate(DB.mortality.slice(-1)[0].date)}. Sebagian besar terjadi di masa brooding (H2–H5: 7 ekor).`;
 if(/modal|biaya/.test(s)){if(!fin)return'Data keuangan tidak tersedia untuk role Anda.';const c=calc.costByCat();return `Modal berjalan siklus #001: ${rp(calc.modal())} (biaya yang sudah disetujui).\n${Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`• ${k}: ${rp(v)}`).join('\n')}\n\nProyeksi biaya sisa siklus ${rp(calc.projectedRemainingCost())}. Ada 1 pembelian pakan ${rp(10400000)} yang masih menunggu approval dan belum dihitung.`;}
 if(/laba|omzet|untung|roi/.test(s)){if(!fin)return'Data keuangan tidak tersedia untuk role Anda.';return `Estimasi laba siklus #001: ${rp(calc.estProfit())} (ROI ${pct(calc.roi())}).\n\nPerhitungan:\n• Estimasi omzet ${rp(calc.estRevenue())} = ${num(calc.projectedPop())} ekor × ~${num(MASTER.targetBobotMin*1.1,2)} kg × ${rp(MASTER.hargaJualHidupKg)}/kg\n• Modal berjalan ${rp(calc.modal())}\n• Proyeksi biaya sisa ${rp(calc.projectedRemainingCost())}\n\nIni estimasi. Angka final baru pasti setelah panen ditimbang dan dijual.`;}
 if(/bobot|berat|target/.test(s)){const g=calc.weightGap();return `Bobot rata-rata ${num(calc.avgWeight(),2)} kg pada H${calc.day()}, target kurva ${num(calc.target(calc.day()),2)} kg — ${g<0?'tertinggal':'di atas target'} ${num(Math.abs(g),1)}%. Kandang A ${num(calc.avgWeight('A'),2)} kg, Kandang B ${num(calc.avgWeight('B'),2)} kg. Untuk mencapai ${MASTER.targetBobotMin} kg di H45 dibutuhkan ADG ~${num((MASTER.targetBobotMin-calc.avgWeight())/(45-calc.day())*1000,0)} g/hari.`;}
 if(/stok.*pakan|pakan.*(aman|stok)/.test(s)){const fd=calc.feedDiff();return `Stok pakan teoritis ${num(calc.feedStockTheory())} kg, cukup untuk ${num(calc.feedDaysLeft(),0)} hari pada ${num(calc.feedAvg7(),0)} kg/hari — ${calc.feedDaysLeft()>=MASTER.minStokPakanHari?'aman':'KRITIS'} (minimum ${MASTER.minStokPakanHari} hari). Sisa siklus ${DB.cycle.targetDays-calc.day()} hari butuh ±${num((DB.cycle.targetDays-calc.day())*calc.feedAvg7()*1.15)} kg, jadi stok saat ini ${calc.feedStockTheory()>=(DB.cycle.targetDays-calc.day())*calc.feedAvg7()*1.15?'mencukupi hingga panen':'belum cukup hingga panen'}.${fd&&Math.abs(fd.diff)>=10?`\n\nCatatan: opname ${fmtDate(fd.op.date)} menunjukkan selisih ${num(fd.diff)} kg yang perlu diverifikasi.`:''}`;}
 if(/populasi|berapa bebek|ekor/.test(s))return `Populasi aktif ${num(calc.population())} ekor (Kandang A ${num(calc.population('A'))}, Kandang B ${num(calc.population('B'))}). Berasal dari ${DB.cycle.dodQty} DOD − ${calc.mortTotal()} mati − ${calc.popBalance().jual} terjual.`;
 if(/anomali|masalah|perhatian/.test(s)){const an=calc.anomalies().filter(a=>a.state.status==='OPEN');return an.length?`Ada ${an.length} temuan yang perlu verifikasi:\n${an.map(a=>'• '+a.title).join('\n')}`:'Tidak ada anomali terbuka saat ini.';}
 if(/approval|persetujuan|setuju/.test(s)){const p=calc.pendingApprovals();return p.length?`${p.length} permintaan menunggu:\n${p.map(x=>'• '+x.title+' — '+userName(x.by)).join('\n')}`:'Tidak ada permintaan yang menunggu.';}
 return 'Data belum cukup untuk menjawab. Saya hanya menjawab dari data yang tercatat di sistem (populasi, pakan, bobot, FCR, stok, keuangan, anomali, approval). Coba pertanyaan lain atau pilih contoh di bawah.';}
function aiDrawer(){return `<div class="modal-bg" data-act="ai-close-bg" style="place-items:stretch end;padding:0;background:rgba(3,14,10,.45)"><div class="drawer" data-stop><div class="dh"><b>${ic('ai',16)} Tanya Farm AI</b><button class="iconbtn" style="width:32px;height:32px" data-act="ai-close">${ic('x',16)}</button></div><div class="db" id="ai-body">${state.aiMsgs.length?state.aiMsgs.map(m=>`<div class="msg ${m.r}">${esc(m.t)}</div>`).join(''):`<div class="msg ai">Halo ${state.user.name.split(' ')[0]}. Saya menjawab hanya dari data sistem Siklus #001 (hari ke-${calc.day()}). Tidak ada angka yang dikarang.</div>`}<div class="chips">${AI_Q.map(q=>`<button class="chip" data-act="ai-ask" data-q="${q}">${q}</button>`).join('')}</div></div><div class="df"><form class="row" data-act="ai-submit" style="flex-wrap:nowrap"><input name="q" placeholder="Tulis pertanyaan…" style="flex:1;background:rgba(255,255,255,.06);border:1px solid var(--line2);border-radius:10px;padding:10px 12px;color:var(--text);min-width:0"><button class="btn primary">Kirim</button></form></div></div></div>`;}

/* ---------------- PUBLIC WEBSITE ---------------- */
function renderSite(){const p=DB.products;return `<div class="site">
 <nav class="site-nav"><div class="wrap"><div class="row" style="gap:10px"><img src="/img/logo-mark.png" alt="" style="width:40px;height:auto"><div><b style="color:#174A3A;font-size:16px;letter-spacing:.02em">AR-FARM</b><small style="display:block;color:#5F6B66;font-size:10px;letter-spacing:.14em">MODERN DUCK FARMING</small></div></div><div class="links"><a href="#tentang">Tentang</a><a href="#produk">Produk</a><a href="#cara">Cara Pesan</a><a href="#faq">FAQ</a><a href="#kontak">Kontak</a></div><button class="btn-site green" style="margin-left:auto;padding:9px 14px" data-act="modal" data-m="siteorder">Pesan Sekarang</button><button class="btn-site" style="background:transparent;color:#174A3A;padding:9px 6px" data-act="site-exit" title="Kembali ke aplikasi">${ic('lock',16)}</button></div></nav>
 <header class="site-hero"><div class="wrap"><div><div class="eyebrow">Sidoarjo · Jawa Timur</div><h1>Premium Peking Duck<br>Langsung dari Peternakan</h1><p>Bebek Peking dibesarkan dengan pakan terukur, kandang bersih, dan pencatatan digital setiap hari. Setiap ekor bisa ditelusuri asal siklusnya.</p><div class="row"><button class="btn-site gold" data-act="modal" data-m="siteorder">PESAN SEKARANG</button><a class="btn-site outline" href="#produk">Lihat Produk</a></div></div><img class="art" src="/img/logo-full.png" alt="AR-FARM" style="width:100%;max-width:420px;margin:0 auto;display:block"></div></header>
 <div class="wrap"><div class="stat-strip"><div><b class="num">${num(calc.population())}</b><small>ekor siap panen ${fmtDate(dateOfDay(DB.cycle.targetDays))}</small></div><div><b class="num">${num(calc.avgWeight(),2)} kg</b><small>bobot rata-rata hari ini</small></div><div><b class="num">${pct(calc.mortPct())}</b><small>tingkat mortalitas (target &lt;5%)</small></div><div><b>Harian</b><small>pencatatan pakan & kesehatan</small></div></div></div>
 <section id="tentang"><div class="wrap" style="display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:center"><div><div class="eyebrow">Tentang Kami</div><h2>Peternakan kecil, standar besar.</h2><p class="lead">AR-FARM memelihara ${DB.cycle.dodQty} ekor per siklus di Sidoarjo. Kami mencatat setiap kg pakan, setiap penimbangan, dan setiap tindakan kesehatan secara digital, sehingga kualitas bisa dipertanggungjawabkan, bukan sekadar dijanjikan.</p></div><div class="feat-grid" style="margin-top:0"><div class="feat"><div class="ic">${ic('leaf',20)}</div><b>Pakan terukur</b><p>Rasio pakan (FCR) dipantau harian.</p></div><div class="feat"><div class="ic">${ic('shield',20)}</div><b>Tertelusur</b><p>Setiap ekor terikat pada siklus & kandang.</p></div><div class="feat"><div class="ic">${ic('heart',20)}</div><b>Sehat</b><p>Vaksinasi terjadwal, masa henti obat dipatuhi.</p></div><div class="feat"><div class="ic">${ic('truck',20)}</div><b>Fresh</b><p>Potong & kirim di hari yang sama.</p></div></div></div></section>
 <section id="produk" style="background:#EFE9DB"><div class="wrap"><div class="eyebrow">Produk & Stok</div><h2>Pilih sesuai kebutuhan dapur Anda.</h2><p class="lead">Stok di bawah ini diambil langsung dari sistem inventory kami dan diperbarui otomatis.</p><div class="prod-grid">${p.map(x=>{const st=calc.stockStatus(x);const stock=calc.productStock(x);return `<div class="prod"><div class="img"><span class="sbadge s-${st.k} stk">${st.t}</span><div style="width:150px">${DUCK_ART(1)}</div></div><div class="body"><h3>${x.name}</h3><p style="color:#5F6B66;font-size:13.5px">${x.desc}</p><div class="price">${rp(MASTER[x.priceKg])}<small>/kg</small></div><div class="meta"><span>⚖ ~${num(x.avgW,2)} kg/ekor</span><span>📦 Stok: <b>${st.k==='out'?'Habis':num(stock)+' ekor'}</b></span><span>Min. order ${x.minOrder} ekor</span></div><div style="margin-top:auto;padding-top:8px"><button class="btn-site ${st.k==='out'?'':'wa'}" style="width:100%;${st.k==='out'?'background:#DDD;color:#888;cursor:not-allowed':''}" ${st.k==='out'?'disabled':''} data-act="modal" data-m="siteorder" data-product="${x.id}">${ic('wa',16)} Pesan via WhatsApp</button></div></div></div>`;}).join('')}</div></div></section>
 <section id="cara"><div class="wrap"><div class="eyebrow">Cara Pemesanan</div><h2>Empat langkah, tanpa ribet.</h2><div class="steps">${[['Pilih produk','Tentukan hidup, potong, atau karkas beserta jumlah ekor.'],['Isi form & kirim WA','Data pesanan masuk ke sistem kami dan Anda diarahkan ke WhatsApp.'],['Konfirmasi & DP','Admin mengonfirmasi ketersediaan, berat estimasi, dan jadwal.'],['Timbang & serah terima','Total final mengikuti berat timbang saat serah terima. Pembayaran pelunasan.']].map(([b,d],i)=>`<div><span class="n">0${i+1}</span><b>${b}</b><p>${d}</p></div>`).join('')}</div></div></section>
 <section class="site-dark"><div class="wrap"><div class="eyebrow">Keunggulan</div><h2>Kenapa restoran memilih kami.</h2><div class="feat-grid">${[['scale','Bobot konsisten','Sortir bobot 1,5–1,8 kg, seragam untuk porsi restoran.'],['report','Laporan siklus','Data pakan, kesehatan, dan mortalitas siklus tersedia atas permintaan.'],['clock','Tepat waktu','Jadwal panen diumumkan 2 minggu sebelumnya untuk pre-order.'],['star','Rasa Peking asli','Strain Peking murni, daging tebal, kulit tipis.']].map(([i,b,d])=>`<div class="feat" style="background:rgba(255,255,255,.06)"><div class="ic" style="background:rgba(198,161,91,.2);color:#C6A15B">${ic(i,20)}</div><b style="color:#fff">${b}</b><p style="color:#CFE0D3">${d}</p></div>`).join('')}</div></div></section>
 <section><div class="wrap"><div class="eyebrow">Testimoni</div><h2>Kata pelanggan kami.</h2><div class="testi">${[['"Bobotnya rata, tidak ada yang kekecilan. Cocok buat menu bebek peking panggang kami."','RM Bebek Goreng Pak Slamet','Rumah makan · pelanggan sejak siklus #000'],['"Suka karena bisa lihat stok dan jadwal panen dulu sebelum pesan."','Ibu Rina','Pelanggan retail'],['"Karkasnya bersih, packing vacuum rapi, dikirim sesuai jadwal."','Restoran Sari Rasa','Restoran']].map(([q,n,r])=>`<div><span style="color:#C6A15B">★★★★★</span><p style="margin-top:8px">${q}</p><b>${n}</b><small>${r}</small></div>`).join('')}</div></div></section>
 <section id="faq" style="background:#EFE9DB"><div class="wrap faq"><div class="eyebrow">FAQ</div><h2>Pertanyaan umum.</h2>${[['Berapa minimum order?','Hidup 10 ekor, potong 2 ekor, karkas 5 ekor. Restoran bisa negosiasi harga untuk order rutin.'],['Apakah bisa kirim?','Ya, untuk Sidoarjo dan Surabaya. Di luar itu ambil di peternakan.'],['Kapan panen berikutnya?','Siklus #001 dijadwalkan panen '+fmtLong(dateOfDay(DB.cycle.targetDays))+'. Pre-order dibuka sekarang.'],['Bagaimana pembayaran?','DP 50% saat konfirmasi, pelunasan saat serah terima sesuai berat timbang.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>
 <section id="kontak"><div class="wrap" style="display:grid;grid-template-columns:1fr 1fr;gap:30px"><div><div class="eyebrow">Kontak</div><h2>Hubungi kami.</h2><p class="lead">AR-FARM · Sidoarjo, Jawa Timur<br>WhatsApp: <b>0812-1111-2203</b> (Admin, 08.00–17.00)<br>Email: halo@argrupfarmindonesia.my.id</p></div><div style="background:#fff;border-radius:16px;padding:24px;box-shadow:0 12px 30px rgba(23,74,58,.1)"><b style="color:#174A3A;font-size:18px">Siap pesan?</b><p style="color:#5F6B66;margin:6px 0 14px">Isi form singkat, pesanan langsung tercatat dan Anda diarahkan ke WhatsApp.</p><button class="btn-site gold" style="width:100%" data-act="modal" data-m="siteorder">PESAN SEKARANG</button></div></div></section>
 <footer class="site-foot"><div class="wrap"><span>© 2026 AR-FARM · Modern Duck Farming</span><span>Stok & jadwal panen tersinkron dengan sistem manajemen peternakan · DEMO</span></div></footer></div>`;}

/* ---------------- LOGIN ---------------- */
function liveBox(){
  const p=state.publicStats;
  const cell=(v,l)=>`<div><b class="num">${v}</b><span>${l}</span></div>`;
  if(!p) return `<div class="livebox"><div class="lhead"><b>Kondisi farm saat ini</b></div><div class="live-grid">${cell('—','Populasi')}${cell('—','Bobot rata-rata')}${cell('—','Mortalitas')}${cell('—','Panen')}</div><div class="live-foot">Menghubungi server…</div></div>`;
  if(!p.cycle) return `<div class="livebox"><div class="lhead"><b>Belum ada siklus aktif</b></div><div class="live-foot">Angka akan muncul di sini begitu siklus pertama dimulai.</div></div>`;
  const hv=p.harvestDate?new Date(p.harvestDate):null;
  return `<div class="livebox">
    <div class="lhead"><b>Kondisi farm saat ini · Siklus ${p.cycle}</b><span class="live-dot"><i></i>Langsung dari server</span></div>
    <div class="live-grid">
      ${cell(num(p.population)+' <small style="font-size:12px;color:var(--muted);font-weight:600">ekor</small>','Populasi aktif')}
      ${cell(p.avgWeightKg?num(p.avgWeightKg,2)+' <small style="font-size:12px;color:var(--muted);font-weight:600">kg</small>':'—','Bobot rata-rata')}
      ${cell(pct(p.mortalityPct),'Mortalitas')}
      ${cell(hv?fmtDate(hv).replace(/ \d{4}$/,''):'—','Estimasi panen')}
    </div>
    <div class="live-foot">Dihitung dari transaksi yang tercatat hari ini, bukan angka yang diketik ulang.</div>
  </div>`;
}
function renderLogin(){const roles=[['OWNER','Hendra Wijaya','Semua akses, approve, keuangan','081211112201'],['MANAGER','Sari Handayani','Operasional & approval','081211112202'],['ADMIN','Dewi Lestari','Pembelian, penjualan, master data','081211112203'],['ANAK_KANDANG','Budi Santoso','Input harian · Kandang A','085722223301']];const sel=state.loginRole||'OWNER';
 return `<div class="login"><div class="login-visual"><div><div class="brand"><img class="brandmark" src="/img/logo-mark.png" alt=""><div><b style="font-size:20px;letter-spacing:.03em">AR-FARM</b><div class="tagline">Modern Duck Farming</div></div></div><h1 style="margin-top:40px">Lihat kondisi farm Anda dalam 10 detik.</h1><p style="color:var(--muted);margin-top:14px;max-width:46ch">Populasi, pakan, bobot, FCR, biaya, dan laba — semua dihitung dari transaksi yang tercatat, bukan angka yang diketik ulang.</p><div class="pillars"><div class="pillar"><b>Tamper-resistant</b><span>Data terkunci, koreksi butuh approval, versi lama tersimpan.</span></div><div class="pillar"><b>Auditable</b><span>Setiap aksi: siapa, kapan, apa, buktinya.</span></div><div class="pillar"><b>Deteksi anomali</b><span>Selisih stok & pola tidak wajar muncul otomatis.</span></div></div></div>${liveBox()}<small style="color:var(--dim)">${demoTag()} &nbsp; v1.0 · data dari server</small></div>
 <div class="login-form"><div class="login-card"><h2>Masuk</h2><p class="sub">Pilih akun demo (password: demo1234) atau masuk dengan akun Anda.</p><div class="role-grid">${roles.map(([r,n,d])=>`<button class="role-btn ${sel===r?'active':''}" data-act="login-role" data-v="${r}"><b>${ROLES[r].label}</b><small>${n}</small><small>${d}</small></button>`).join('')}</div><form class="form" data-act="login"><div class="f"><label>Nomor HP / nama</label><input name="phone" id="login-phone" value="${roles.find(x=>x[0]===sel)[3]}" required autocomplete="username"></div><div class="f"><label>Password</label><input name="password" id="login-pass" type="password" value="demo1234" required autocomplete="current-password"></div><button class="btn primary lg" type="submit" ${state.busy?"disabled":""}>Masuk sebagai ${ROLES[sel].label}</button></form><p style="color:var(--dim);font-size:12px;margin-top:14px;text-align:center">Maks. 5 percobaan / 15 menit · sesi 12 jam</p><div style="text-align:center;margin-top:18px"><button class="btn ghost" data-act="site">${ic('globe',16)} Lihat website publik argrupfarmindonesia.my.id</button></div></div></div></div>`;}

/* ---------------- ROUTER / RENDER ---------------- */
const PAGES={dashboard:pgDashboard,siklus:pgSiklus,populasi:pgPopulasi,pakan:pgPakan,pertumbuhan:pgPertumbuhan,kesehatan:pgKesehatan,keuangan:pgKeuangan,penjualan:pgPenjualan,stok:pgStok,laporan:pgLaporan,persetujuan:pgPersetujuan,pengguna:pgPengguna,pengaturan:pgPengaturan,audit:pgAudit,anomali:pgAnomali};
const AK={'ak-home':akHome,'ak-input':akInputMenu,'ak-kandang':akKandang,'ak-riwayat':akRiwayat,'ak-pakan':akPakan,'ak-mati':akMati,'ak-timbang':akTimbang,'ak-kondisi':akKondisi,'ak-sehat':akSehat,'ak-success':akSuccess};
function render(){const root=document.getElementById('root');if(state.view!=='site'&&state.user&&!DB){root.innerHTML='<div class="login-form" style="height:100%"><div class="login-card">'+skeleton()+'</div></div>';return;}
 if(state.view==='site'){root.innerHTML=renderSite();root.querySelector('.site').scrollTop=0;renderLayer();return;}
 if(!state.user){root.innerHTML=renderLogin();renderLayer();return;}
 if(state.user.role==='ANAK_KANDANG'){const p=AK[state.page]?state.page:'ak-home';const active=p.startsWith('ak-')&&['ak-home','ak-input','ak-kandang','ak-riwayat'].includes(p)?p:(p==='ak-success'?'ak-home':'ak-input');root.innerHTML=akShell(state.loading?skeleton():AK[p](),active);renderLayer();return;}
 const fn=PAGES[state.page];const html=state.loading?skeleton():(canPage(state.page)&&fn?fn():denied());root.innerHTML=renderShell(html);renderLayer();if(!state.loading)requestAnimationFrame(drawCharts);}
function go(page){state.page=page;state.tab=null;state.notif=false;state.sideOpen=false;state.loading=true;render();const c=document.getElementById('content');if(c)c.scrollTop=0;setTimeout(()=>{state.loading=false;render();},260);}
const fd=form=>Object.fromEntries(new FormData(form).entries());
function formPhotoName(form){const f=form.querySelector('input[type=file]');return f&&f.files&&f.files[0]?f.files[0].name:'IMG-'+Date.now().toString().slice(-6)+'.jpg';}

