
/* ---------------- ICONS ---------------- */
const IC={
 home:'<path d="M3 11l9-8 9 8v9a2 2 0 0 1-2 2h-4v-6H9v6H5a2 2 0 0 1-2-2z"/>',
 cycle:'<path d="M21 12a9 9 0 1 1-2.6-6.4"/><path d="M21 3v6h-6"/>',
 duck:'<path d="M4 15c0 3 3 5 8 5s8-2 8-5c0-2-1.5-3-3-3H9V9a3 3 0 1 1 6 0"/><circle cx="14" cy="8" r="1"/>',
 feed:'<path d="M4 8h16l-1.5 11a2 2 0 0 1-2 2h-9a2 2 0 0 1-2-2z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',
 growth:'<path d="M3 17l6-6 4 4 8-8"/><path d="M14 7h7v7"/>',
 heart:'<path d="M12 21s-7-4.6-9.5-9A5.5 5.5 0 0 1 12 6a5.5 5.5 0 0 1 9.5 6c-2.5 4.4-9.5 9-9.5 9z"/>',
 money:'<rect x="2" y="6" width="20" height="12" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M6 12h.01M18 12h.01"/>',
 cart:'<circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.7 13.4a2 2 0 0 0 2 1.6h9.7a2 2 0 0 0 2-1.6L23 6H6"/>',
 box:'<path d="M21 8l-9-5-9 5v8l9 5 9-5z"/><path d="M3 8l9 5 9-5M12 13v9"/>',
 report:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6M8 13h8M8 17h5"/>',
 check:'<path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',
 users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',
 gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0 1.8.3H9a1.7 1.7 0 0 0 1-1.5V3a2 2 0 1 1 4 0v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.7 1.7 0 0 0-.3 1.8V9a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1z"/>',
 shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>',
 alert:'<path d="M10.3 3.9L1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z"/><path d="M12 9v4M12 17h.01"/>',
 ai:'<path d="M12 2l1.8 5.2L19 9l-5.2 1.8L12 16l-1.8-5.2L5 9l5.2-1.8z"/><path d="M19 16l.9 2.1L22 19l-2.1.9L19 22l-.9-2.1L16 19l2.1-.9z"/>',
 bell:'<path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/>',
 search:'<circle cx="11" cy="11" r="8"/><path d="M21 21l-4.3-4.3"/>',
 menu:'<path d="M3 6h18M3 12h18M3 18h18"/>',
 x:'<path d="M18 6L6 18M6 6l12 12"/>',
 camera:'<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/>',
 skull:'<circle cx="12" cy="10" r="7"/><path d="M9 17v4h6v-4M9.5 11h.01M14.5 11h.01"/>',
 scale:'<path d="M12 3v18M3 7h18M5 7l-3 7a4 4 0 0 0 6 0L5 7M19 7l-3 7a4 4 0 0 0 6 0l-3-7"/>',
 barn:'<path d="M3 21V9l9-6 9 6v12"/><path d="M9 21v-8h6v8M3 21h18"/>',
 clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
 out:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>',
 arrow:'<path d="M5 12h14M12 5l7 7-7 7"/>',
 dl:'<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 globe:'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 0 20 15 15 0 0 1 0-20z"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
 lock:'<rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
 history:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',
 wa:'<path d="M20.5 3.5A11 11 0 0 0 3.2 16.8L2 22l5.3-1.2A11 11 0 1 0 20.5 3.5z"/><path d="M8.5 9.5c.5 3 3 5.5 6 6l1.5-1.5-2-1-1 1a5 5 0 0 1-2.5-2.5l1-1-1-2z"/>',
 star:'<path d="M12 2l3.1 6.3 6.9 1-5 4.9 1.2 6.8L12 17.8 5.8 21l1.2-6.8-5-4.9 6.9-1z"/>',
 leaf:'<path d="M11 20A7 7 0 0 1 4 13c0-5 4-9 13-9 0 9-4 13-6 16z"/><path d="M4 21c3-4 6-7 9-9"/>',
 truck:'<path d="M1 3h15v13H1zM16 8h4l3 3v5h-7z"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/>',
 pen:'<path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/>',
};
const ic=(n,s=18)=>`<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">${IC[n]||''}</svg>`;
const DUCK_ART=(op=1)=>`<svg viewBox="0 0 320 240" fill="none" style="opacity:${op}"><defs><linearGradient id="dg" x1="0" x2="1"><stop offset="0" stop-color="#F7F8F5"/><stop offset="1" stop-color="#C9D6CB"/></linearGradient></defs>
<ellipse cx="160" cy="215" rx="140" ry="14" fill="rgba(0,0,0,.25)"/>
<path d="M60 160c0-40 40-70 95-70 45 0 80 20 100 48l40-18-5 30-30 12c-6 38-48 58-105 58-60 0-95-24-95-60z" fill="url(#dg)"/>
<path d="M150 92c-30-6-40-30-30-52 12-26 52-26 66 0 8 16 4 32-8 44" fill="url(#dg)"/>
<circle cx="182" cy="46" r="5" fill="#1F2933"/><path d="M196 52l38 10-36 12z" fill="#D99A2B"/>
<path d="M80 160c20 10 60 12 100 4" stroke="#A9B8AF" stroke-width="3" stroke-linecap="round"/></svg>`;

/* ---------------- UI HELPERS ---------------- */
const badge=(k,t)=>`<span class="badge b-${k}">${t}</span>`;
const stBadge=s=>({APPROVED:badge('approved','DISETUJUI'),PENDING:badge('pending','MENUNGGU'),PENDING_APPROVAL:badge('pending','MENUNGGU APPROVAL'),REJECTED:badge('rejected','DITOLAK'),RECORDED:badge('info','TERCATAT'),LOCKED:badge('neutral','TERKUNCI'),NEW:badge('gold','BARU'),CONFIRMED:badge('info','DIKONFIRMASI'),PAID:badge('ok','DIBAYAR'),UNPAID:badge('warn','BELUM BAYAR'),PREPARING:badge('info','DISIAPKAN'),READY:badge('ok','SIAP'),DELIVERED:badge('ok','TERKIRIM'),CANCELLED:badge('danger','DIBATALKAN'),AKTIF:badge('ok','AKTIF'),SELESAI:badge('neutral','SELESAI'),OPEN:badge('warn','PERLU VERIFIKASI'),VERIFIED:badge('ok','TERVERIFIKASI'),NORMAL:badge('ok','NORMAL'),WARNING:badge('warn','WARNING'),CRITICAL:badge('danger','CRITICAL')}[s]||badge('neutral',s));
const kpi=(lbl,val,unit,foot,footCls='',icon='growth',cls='')=>`<div class="kpi ${cls}"><div class="ic">${ic(icon,18)}</div><div class="lbl">${lbl}</div><div class="val num">${val}${unit?`<small>${unit}</small>`:''}</div><div class="foot ${footCls}">${foot||''}</div></div>`;
const emptyState=(t,d,act='')=>`<div class="empty">${ic('box',30)}<b>${t}</b><span>${d}</span>${act}</div>`;
const seg=(opts,cur,act)=>`<div class="seg">${opts.map(([v,l])=>`<button class="${cur===v?'active':''}" data-act="${act}" data-v="${v}">${l}</button>`).join('')}</div>`;
const rangeSeg=()=>seg([['7','7 hari'],['14','14 hari'],['30','30 hari'],['siklus','1 siklus']],state.range,'range');
const rangeDays=()=>state.range==='siklus'?calc.day():Math.min(calc.day(),+state.range);
const lastN=(a,n)=>a.slice(Math.max(0,a.length-n));
const dayLabels=n=>{const d=calc.day();const out=[];for(let i=d-n+1;i<=d;i++)out.push('H'+i);return out;};
const toast=(msg,k='ok')=>{const w=document.getElementById('toasts');const t=document.createElement('div');t.className='toast '+k;t.innerHTML=`${ic(k==='ok'?'check':k==='err'?'alert':'alert',18)}<span>${msg}</span>`;w.appendChild(t);setTimeout(()=>t.remove(),3200);};
const photoChip=p=>p?(String(p).startsWith('/uploads/')?`<a class="thumb" href="${p}" target="_blank" rel="noopener" title="Lihat bukti">${ic('camera',14)}</a>`:`<span class="thumb" title="${p}">${ic('camera',14)}</span>`):'<span class="badge b-neutral">—</span>';
const demoTag=()=>`<span class="demo-tag">${ic('alert',12)} DEMO DATA</span>`;

/* ---------------- CHARTS ---------------- */
let charts=[];
const CHART_DEF={color:'#A9B8AF',grid:'rgba(255,255,255,.07)'};
function mkChart(id,cfg){const el=document.getElementById(id);if(!el)return;const c=new Chart(el,cfg);charts.push(c);}
function baseOpts(extra={}){return Object.assign({responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:CHART_DEF.color,boxWidth:10,usePointStyle:true,font:{family:'Plus Jakarta Sans',size:11}}},tooltip:{backgroundColor:'#0B241C',borderColor:'rgba(255,255,255,.15)',borderWidth:1,titleColor:'#fff',bodyColor:'#EDF2EE'}},scales:{x:{ticks:{color:CHART_DEF.color,font:{size:10},maxTicksLimit:10},grid:{color:CHART_DEF.grid}},y:{ticks:{color:CHART_DEF.color,font:{size:10}},grid:{color:CHART_DEF.grid},beginAtZero:true}}},extra);}
function lineDs(label,data,color,fill=false,dash=null){return{label,data,borderColor:color,backgroundColor:fill?color.replace(')',',.18)').replace('rgb','rgba'):color,fill,tension:.35,borderWidth:2,pointRadius:data.filter(x=>x!=null).length>20?0:3,pointHoverRadius:5,borderDash:dash||[],spanGaps:true};}
const C_GREEN='rgb(168,208,141)',C_GOLD='rgb(198,161,91)',C_RED='rgb(217,83,79)',C_SAGE='rgb(127,166,140)',C_WARN='rgb(217,154,43)',C_WHITE='rgb(237,242,238)';
function chartCard(title,id,extra='',h='',sub='')
{return `<div class="card"><div class="card-h"><div><h3>${title}</h3>${sub?`<div class="sub">${sub}</div>`:''}</div>${extra}</div><div class="chart-box ${h}"><canvas id="${id}"></canvas></div></div>`;}
function drawCharts(){
  charts.forEach(c=>c.destroy());charts=[];
  const n=rangeDays(),labels=dayLabels(n),days=[...Array(calc.day()).keys()].map(i=>i+1);
  const ws=calc.weightSeries();
  // Weight actual vs target (full cycle)
  const tLabels=[...Array(DB.cycle.targetDays).keys()].map(i=>'H'+(i+1));
  const target=tLabels.map((_,i)=>calc.target(i+1));const actual=tLabels.map((_,i)=>{const p=ws.find(w=>w.day===i+1);return p?+p.avg.toFixed(3):null;});
  const wOpts=baseOpts();wOpts.scales.y.title={display:true,text:'kg',color:CHART_DEF.color};
  mkChart('ch-weight',{type:'line',data:{labels:tLabels,datasets:[lineDs('Aktual',actual,C_GREEN,true),lineDs('Target',target,C_WHITE,false,[5,5])]},options:wOpts});
  // Feed
  const fb=calc.feedByDay();const avg=fb.map((_,i)=>{const s=fb.slice(Math.max(0,i-6),i+1);return +(s.reduce((a,b)=>a+b,0)/s.length).toFixed(1);});
  mkChart('ch-feed',{type:'bar',data:{labels,datasets:[{label:'Pakan (kg)',data:lastN(fb,n),backgroundColor:'rgba(168,208,141,.75)',borderRadius:6},lineDs('Rata-rata 7 hari',lastN(avg,n),C_GOLD,false,[4,4])]},options:baseOpts()});
  // FCR
  const fs=calc.fcrSeries();mkChart('ch-fcr',{type:'line',data:{labels:fs.map(x=>'H'+x.day),datasets:[lineDs('FCR',fs.map(x=>x.fcr?+x.fcr.toFixed(2):null),C_GOLD,true)]},options:baseOpts()});
  // Mortality
  const mb=calc.mortByDay();mkChart('ch-mort',{type:'bar',data:{labels,datasets:[{label:'Mati (ekor)',data:lastN(mb,n),backgroundColor:'rgba(217,83,79,.8)',borderRadius:6}]},options:baseOpts()});
  // Population
  const pop=days.map(d=>calc.population(null,new Date(dateOfDay(d).getTime()+86399000)));
  const pOpts=baseOpts();pOpts.scales.y.beginAtZero=false;pOpts.scales.y.min=Math.floor(Math.min(...pop)/50)*50-50;
  mkChart('ch-pop',{type:'line',data:{labels,datasets:[lineDs('Populasi',lastN(pop,n),C_SAGE,true)]},options:pOpts});
  // Finance: cost by category doughnut + cumulative cost/revenue/profit line
  const cbc=calc.costByCat();const cats=Object.keys(cbc);
  mkChart('ch-cost',{type:'doughnut',data:{labels:cats,datasets:[{data:cats.map(c=>cbc[c]),backgroundColor:['#A8D08D','#7FA68C','#C6A15B','#2E8B57','#D99A2B','#5B8C6E','#8FB29B','#E5C98A','#3F7A5C','#B7C9BD','#6C8E7A','#D9D6CC'],borderColor:'#0B241C',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'right',labels:{color:CHART_DEF.color,boxWidth:10,usePointStyle:true,font:{size:10}}},tooltip:{callbacks:{label:c=>' '+rp(c.parsed)}}}}});
  const cum=[];let acc=0;days.forEach(d=>{const end=new Date(dateOfDay(d).getTime()+86399000);let c=DB.expenses.filter(e=>e.status==='APPROVED'&&e.date<=end).reduce((s,e)=>s+e.amount,0)+DB.feedPurchases.filter(p=>p.status==='APPROVED'&&p.date<=end).reduce((s,p)=>s+p.qty*p.price,0);cum.push(c);});
  const rev=days.map(d=>{const end=new Date(dateOfDay(d).getTime()+86399000);return DB.orders.filter(o=>o.pay==='PAID'&&o.date<=end).reduce((s,o)=>s+calc.orderTotal(o),0);});
  const est=calc.estRevenue();const proj=days.map(d=>Math.round(est*d/DB.cycle.targetDays));
  const fOpts=baseOpts();fOpts.scales.y.ticks.callback=v=>'Rp'+(v/1e6).toFixed(0)+'jt';
  mkChart('ch-fin',{type:'line',data:{labels,datasets:[lineDs('Biaya kumulatif',lastN(cum,n),C_RED,true),lineDs('Omzet realisasi',lastN(rev,n),C_GREEN,true),lineDs('Proyeksi omzet (linear)',lastN(proj,n),C_GOLD,false,[4,4])]},options:fOpts});
  const profit=days.map((d,i)=>rev[i]+proj[i]-cum[i]);
  const prOpts=baseOpts();prOpts.scales.y.beginAtZero=false;prOpts.scales.y.ticks.callback=v=>'Rp'+(v/1e6).toFixed(0)+'jt';
  mkChart('ch-profit',{type:'bar',data:{labels,datasets:[{label:'Proyeksi laba berjalan',data:lastN(profit,n),backgroundColor:lastN(profit,n).map(v=>v>=0?'rgba(168,208,141,.75)':'rgba(217,83,79,.75)'),borderRadius:6}]},options:prOpts});
  // small sparkline for mobile owner? (reuse)
  // barn compare
  const bw=['A','B'].map(b=>calc.avgWeight(b)||0);mkChart('ch-barn',{type:'bar',data:{labels:['Kandang A','Kandang B'],datasets:[{label:'Bobot rata-rata (kg)',data:bw,backgroundColor:['rgba(168,208,141,.8)','rgba(127,166,140,.8)'],borderRadius:8}]},options:baseOpts({indexAxis:'y'})});
}

/* ---------------- SHELL ---------------- */
const NAV=[['dashboard','Dashboard','home'],['siklus','Siklus Ternak','cycle'],['populasi','Populasi & Mortalitas','duck'],['pakan','Pakan','feed'],['pertumbuhan','Pertumbuhan','growth'],['kesehatan','Kesehatan','heart'],['keuangan','Keuangan','money'],['penjualan','Penjualan','cart'],['stok','Stok & Gudang','box'],['laporan','Laporan','report'],['persetujuan','Persetujuan','check'],['pengguna','Pengguna','users'],['pengaturan','Pengaturan','gear']];
const NAV2=[['anomali','Anomali','alert'],['audit','Audit Trail','shield']];
function renderShell(content){
  const u=state.user;const pend=calc.pendingApprovals().length;const notifs=calc.notifications();
  const navBtn=([p,l,i])=>canPage(p)?`<button class="${state.page===p?'active':''}" data-act="go" data-page="${p}">${ic(i)}<span>${l}</span>${p==='persetujuan'&&pend?`<span class="cnt">${pend}</span>`:''}${p==='anomali'&&calc.anomalies().filter(a=>a.state.status==='OPEN').length?`<span class="cnt" style="background:var(--warn);color:#0B241C">${calc.anomalies().filter(a=>a.state.status==='OPEN').length}</span>`:''}</button>`:'';
  return `<div class="app">
  ${state.sideOpen?'<div class="overlay" data-act="side-close"></div>':''}
  <aside class="sidebar ${state.sideOpen?'open':''}">
    <div class="brand"><div class="logo">${DUCK_ART()}</div><div><b>PEKING FARM</b><small>Modern Duck Farming</small></div></div>
    <nav class="nav">${NAV.map(navBtn).join('')}<div class="nav-sec">Integritas Data</div>${NAV2.map(navBtn).join('')}<div class="nav-sec">Publik</div><button data-act="site">${ic('globe')}<span>Website Penjualan</span></button></nav>
    <div class="ai-card"><b>${ic('ai',16)} Tanya Farm AI</b><p>Tanya apa saja tentang populasi, pakan, FCR, stok, atau keuangan siklus ini.</p><button class="btn primary sm" data-act="ai-open">Mulai Chat ${ic('arrow',14)}</button></div>
  </aside>
  <div class="main">
    <div class="demo-band">${DB.farm.name} · Siklus ${DB.cycle.code} · ${fmtLong(DEMO_TODAY)} · hari ke-${calc.day()} · semua angka dihitung dari transaksi</div>
    <header class="topbar">
      <button class="iconbtn hamb" data-act="side-open">${ic('menu')}</button>
      <div class="search">${ic('search',16)}<input id="global-search" placeholder="Cari data, laporan, atau tanya AI…" data-act="search-input"><kbd>⌘K</kbd></div>
      <div style="margin-left:auto;position:relative"><button class="iconbtn" data-act="notif">${ic('bell')}${notifs.length?`<span class="dot">${notifs.length}</span>`:''}</button>
        ${state.notif?`<div class="notif-pop">${notifs.slice(0,7).map(n=>`<div class="it" data-act="go" data-page="${n.page}" style="cursor:pointer"><span style="color:${n.t==='anomaly'?'var(--warn)':n.t==='order'?'var(--gold)':'#F29390'}">${ic(n.t==='anomaly'?'alert':n.t==='order'?'cart':'check',16)}</span><div><b>${n.title}</b><small>${n.sub} · ${fmtDT(n.date)}</small></div></div>`).join('')||'<div class="it">Tidak ada notifikasi.</div>'}</div>`:''}
      </div>
      <div class="cycle-pill">${ic('cycle',16)}<div><b>Siklus ${DB.cycle.code}</b><small>${fmtDate(DB.cycle.dodDate)} – ${fmtDate(dateOfDay(DB.cycle.targetDays))}</small></div></div>
      <div class="user-pill"><span class="avatar">${u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span><b style="display:block;font-size:13px;line-height:1.1">${u.name}</b><small style="color:var(--muted)">${ROLES[u.role].label}</small></span><button class="btn ghost sm" data-act="logout" title="Keluar">${ic('out',16)}</button></div>
    </header>
    <div class="content" id="content">${content}</div>
  </div></div>`;
}
function pageHead(t,d,r=''){return `<div class="page-head"><div><h1>${t}</h1><div class="desc">${d}</div></div><div class="row">${r}</div></div>`;}
function denied(){return `<div class="denied"><div class="lock">${ic('lock',30)}</div><h2>Akses ditolak</h2><p style="color:var(--muted);max-width:44ch">Role <b>${ROLES[state.user.role].label}</b> tidak memiliki izin untuk halaman ini. Hak akses divalidasi di server, bukan hanya disembunyikan di tampilan.</p><button class="btn" data-act="go" data-page="${state.user.role==='ANAK_KANDANG'?'ak-home':'dashboard'}">Kembali</button></div>`;}
function skeleton(){return `<div class="grid g-kpi">${'<div class="skel" style="height:118px"></div>'.repeat(4)}</div><div class="grid g-2" style="margin-top:14px">${'<div class="skel" style="height:260px"></div>'.repeat(2)}</div>`;}

/* ---------------- ATTENTION LIST (Owner control center) ---------------- */
function attentionItems(){
  const items=[];const pend=calc.pendingApprovals().length;const an=calc.anomalies().filter(a=>a.state.status==='OPEN');
  if(pend)items.push(['red',`${pend} persetujuan menunggu`,'persetujuan']);
  const fd=calc.feedDiff();if(fd&&Math.abs(fd.diff)>=10)items.push(['yel',`Selisih stok pakan ${num(Math.abs(fd.diff))} kg — perlu verifikasi`,'stok']);
  const gap=calc.weightGap();if(gap<-3)items.push(['yel',`Bobot tertinggal ${num(Math.abs(gap))}% dari target`,'pertumbuhan']);else items.push(['grn','Bobot sesuai kurva target','pertumbuhan']);
  const dev=(calc.feedToday()-calc.feedAvg7())/calc.feedAvg7()*100;if(Math.abs(dev)>MASTER.batasPakanPct)items.push(['yel',`Konsumsi pakan hari ini ${num(Math.abs(dev))}% ${dev>0?'lebih tinggi':'lebih rendah'} dari rata-rata`,'pakan']);
  const newO=DB.orders.filter(o=>o.status==='NEW').length;if(newO)items.push(['yel',`${newO} order baru dari website belum dikonfirmasi`,'penjualan']);
  DB.inventory.filter(i=>i.qty<i.min).forEach(i=>items.push(['yel',`Stok ${i.name.split(' (')[0]} di bawah minimum`,'stok']));
  items.push([calc.mortPct()<MASTER.targetMortalitasPct?'grn':'red',`Mortalitas ${pct(calc.mortPct())} — ${calc.mortPct()<MASTER.targetMortalitasPct?'normal':'di atas target'}`,'populasi']);
  items.push([calc.feedDaysLeft()>=MASTER.minStokPakanHari?'grn':'red',`Stok pakan cukup untuk ${num(calc.feedDaysLeft(),0)} hari`,'stok']);
  return items;
}
const attentionCard=()=>`<div class="card"><div class="card-h"><h3>Apa yang perlu perhatian saya?</h3><span class="sub">${fmtDT(DEMO_TODAY)}</span></div><div class="attn">${attentionItems().map(([c,t,p])=>`<button data-act="go" data-page="${p}"><span class="dotc d-${c}"></span><span>${t}</span><span class="arr">${ic('arrow',14)}</span></button>`).join('')}</div></div>`;
function healthCard(){const h=calc.healthScore();const col=h.status==='NORMAL'?'#A8D08D':h.status==='WARNING'?'#D99A2B':'#D9534F';const r=50,c=2*Math.PI*r;return `<div class="card"><div class="card-h"><h3>Farm Health Score</h3>${stBadge(h.status)}</div><div class="score"><div class="ring"><svg width="118" height="118" viewBox="0 0 118 118"><circle cx="59" cy="59" r="${r}" stroke="rgba(255,255,255,.1)" stroke-width="10" fill="none"/><circle cx="59" cy="59" r="${r}" stroke="${col}" stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="${c}" stroke-dashoffset="${c*(1-h.score/100)}"/></svg><div class="c"><div><b class="num">${h.score}</b><small>/ 100</small></div></div></div><div class="brk">${h.items.map(([l,v])=>`<div><span>${l}</span><b class="num">${num(v,0)}%</b><div class="bar ${v<70?'w':''}"><i style="width:${v}%"></i></div></div>`).join('')}</div></div><div class="alert ${h.status==='NORMAL'?'ok':h.status==='WARNING'?'warn':'danger'}" style="margin-top:14px">${ic(h.status==='NORMAL'?'check':'alert',18)}<div><b>KONDISI ${h.status}</b>${h.status==='NORMAL'?'Semua parameter dalam batas optimal.':'Ada parameter yang perlu ditindaklanjuti — lihat daftar anomali.'}</div></div></div>`;}

/* ---------------- PAGES ---------------- */
const KPIROW=()=>{const f=calc.fcr();const gap=calc.weightGap();return `<div class="grid g-kpi">
 ${kpi('Populasi Aktif',num(calc.population()),'ekor',`${ic('check',13)} ${pct(calc.population()/DB.cycle.dodQty*100)} dari ${num(DB.cycle.dodQty)} DOD`,'up','duck')}
 ${kpi('Bobot Rata-rata',num(calc.avgWeight(),2),'kg',`<div style="flex:1"><div class="bar ${gap<-3?'w':''}"><i style="width:${Math.min(100,calc.avgWeight()/MASTER.targetBobotMax*100)}%"></i></div></div><span>${gap>=0?'+':''}${num(gap,1)}% vs target</span>`,gap<-3?'warn':'up','scale')}
 ${kpi('Pakan Terpakai',num(calc.feedTotal()),'kg',`Hari ini ${num(calc.feedToday())} kg · ${num(calc.feedTotal()/calc.population(),2)} kg/ekor`,'','feed')}
 ${kpi('Mortalitas',num(calc.mortTotal()),'ekor',`${pct(calc.mortPct())} · ${calc.mortPct()<MASTER.targetMortalitasPct?'Normal (target <'+MASTER.targetMortalitasPct+'%)':'Di atas target'}`,calc.mortPct()<MASTER.targetMortalitasPct?'up':'down','skull','red')}
 ${kpi('FCR',f?num(f.fcr,2):'—','',f?`${num(f.feed)} kg ÷ ${num(f.bio,0)} kg biomassa`:'Data belum cukup',f&&f.fcr>2.3?'warn':'','growth')}
 ${can('finance')?kpi('Modal Berjalan',rp(calc.modal()),'',`${rp(calc.modal()/DB.cycle.dodQty)}/ekor DOD`,'','money','gold'):''}
 ${can('finance')?kpi('Estimasi Omzet',rp(calc.estRevenue()),'',`${num(calc.projectedPop())} ekor × ~${num(MASTER.targetBobotMin*1.1,2)} kg × ${rp(MASTER.hargaJualHidupKg)}`,'','cart','gold'):''}
 ${can('finance')?kpi('Estimasi Laba',rp(calc.estProfit()),'',`ROI ${pct(calc.roi())} · setelah proyeksi biaya sisa ${rp(calc.projectedRemainingCost())}`,calc.estProfit()>0?'up':'down','growth','gold'):''}
</div>`;};
const heroCard=()=>`<div class="hero"><div class="art">${DUCK_ART(.9)}</div><div class="weather">${ic('sun',18)} <b>28°C</b><small>Cerah berawan · ${DB.farm.location}</small></div>
 <div class="row">${stBadge(DB.cycle.status)}<span style="color:var(--muted);font-weight:700">Siklus ${DB.cycle.code}</span></div>
 <h1>${DB.cycle.breed}</h1>
 <div class="meta"><span><b class="num">${num(DB.cycle.dodQty)}</b> DOD</span><span><b class="num">Hari ke-${calc.day()}</b> dari ${DB.cycle.targetDays}</span><span>Fase <b>${DB.cycle.stage}</b></span><span>Estimasi panen <b>${fmtDate(dateOfDay(DB.cycle.targetDays))}</b></span></div>
 <div class="bar" style="max-width:420px;margin-top:6px"><i style="width:${calc.day()/DB.cycle.targetDays*100}%"></i></div></div>`;
const recentActivity=(n=6)=>`<div class="card"><div class="card-h"><h3>Aktivitas Terbaru</h3><button class="btn ghost sm" data-act="go" data-page="audit">Lihat audit trail ${ic('arrow',12)}</button></div><div class="tbl-wrap"><table><thead><tr><th>Waktu</th><th>Aktivitas</th><th>User</th><th>Bukti</th></tr></thead><tbody>${DB.audit.filter(a=>['CREATE','CORRECTION','STOCK_OPNAME'].includes(a.action)).slice(0,n).map(a=>`<tr><td class="num">${fmtDT(a.date)}</td><td style="white-space:normal">${a.detail}</td><td>${userName(a.user)}<br><small style="color:var(--dim)">${userRole(a.user)}</small></td><td>${a.detail.includes('Bukti')||a.entity==='Mortality'||a.entity==='WeightRecord'?photoChip('x'):'—'}</td></tr>`).join('')}</tbody></table></div></div>`;
const anomalyCard=(n=4)=>{const list=calc.anomalies().filter(a=>a.state.status==='OPEN').slice(0,n);return `<div class="card"><div class="card-h"><h3>Peringatan & Anomali</h3><button class="btn ghost sm" data-act="go" data-page="anomali">Lihat semua ${ic('arrow',12)}</button></div><div style="display:flex;flex-direction:column;gap:8px">${list.length?list.map(a=>`<div class="alert ${a.sev==='info'?'info':a.sev}">${ic('alert',16)}<div style="flex:1"><b>${a.title}</b><small style="color:var(--muted)">${fmtDT(a.date)} · ${stBadge('OPEN')}</small></div><button class="btn sm" data-act="go" data-page="${a.page}">Cek</button></div>`).join(''):emptyState('Tidak ada anomali','Semua parameter dalam batas normal.')}</div></div>`;};
const approvalCard=(n=3)=>{const list=calc.pendingApprovals().slice(0,n);return `<div class="card"><div class="card-h"><h3>Persetujuan Menunggu ${list.length?`<span class="badge b-danger">${calc.pendingApprovals().length}</span>`:''}</h3><button class="btn ghost sm" data-act="go" data-page="persetujuan">Lihat semua ${ic('arrow',12)}</button></div><div style="display:flex;flex-direction:column;gap:8px">${list.length?list.map(p=>`<div class="alert info" style="align-items:center">${ic(p.kind==='CORRECTION'?'pen':p.kind==='ORDER'?'cart':'feed',16)}<div style="flex:1;min-width:0"><b>${p.title}</b><small style="color:var(--muted)">${p.sub} · ${userName(p.by)}</small></div>${can('approve')?`<button class="btn danger sm" data-act="reject" data-id="${p.id}" data-kind="${p.kind}">Tolak</button><button class="btn ok sm" data-act="approve" data-id="${p.id}" data-kind="${p.kind}">Setujui</button>`:stBadge('PENDING')}</div>`).join(''):emptyState('Tidak ada yang menunggu','Semua transaksi sudah diproses.')}</div></div>`;};

function pgDashboard(){
  const role=state.user.role;
  if(role==='MANAGER')return pgDashboardManager();
  if(role==='ADMIN')return pgDashboardAdmin();
  return `${heroCard()}<div style="height:14px"></div>${KPIROW()}
  <div class="grid g-3" style="margin-top:14px">${attentionCard()}${healthCard()}
   <div class="card"><div class="card-h"><h3>Aliran Populasi</h3><span class="sub">Prinsip balance</span></div>${popFlow()}<div class="chart-box sm" style="margin-top:10px"><canvas id="ch-pop"></canvas></div></div></div>
  <div class="grid g-2" style="margin-top:14px">${chartCard('Pertumbuhan Bobot','ch-weight','','','Aktual vs kurva target · kg')}${chartCard('Konsumsi Pakan','ch-feed',rangeSeg(),'','kg per hari')}</div>
  <div class="grid g-3" style="margin-top:14px">${chartCard('FCR','ch-fcr','','sm','Pakan ÷ pertambahan biomassa')}${chartCard('Mortalitas','ch-mort','','sm','ekor per hari')}${feedStockCard()}</div>
  <div class="grid g-2" style="margin-top:14px">${chartCard('Biaya vs Omzet','ch-fin','','','kumulatif · Rp')}${financeCycleCard()}</div>
  <div class="grid g-3" style="margin-top:14px">${recentActivity()}${anomalyCard()}${approvalCard()}</div>`;
}
function pgDashboardManager(){return `${heroCard()}<div style="height:14px"></div>${KPIROW()}
 <div class="grid g-3" style="margin-top:14px">${approvalCard(4)}${anomalyCard(4)}${healthCard()}</div>
 <div class="grid g-2" style="margin-top:14px">${chartCard('Konsumsi Pakan','ch-feed',rangeSeg(),'','kg per hari')}${chartCard('Mortalitas','ch-mort',rangeSeg(),'','ekor per hari')}</div>
 <div class="grid g-3" style="margin-top:14px">${barnPerfCard()}${feedStockCard()}${chartCard('Pertumbuhan Bobot','ch-weight','','sm')}</div>
 <div class="grid g-2" style="margin-top:14px">${barnCondCard()}${recentActivity(5)}</div>
 `;}
function pgDashboardAdmin(){const newO=DB.orders.filter(o=>o.status==='NEW');return `${heroCard()}<div style="height:14px"></div><div class="grid g-kpi">
 ${kpi('Order Baru (Website)',newO.length,'order',newO.length?'Perlu dikonfirmasi':'Tidak ada','warn','cart','gold')}
 ${kpi('Penjualan Bulan Ini',rp(DB.orders.filter(o=>o.pay==='PAID'&&o.date.getMonth()===8).reduce((s,o)=>s+calc.orderTotal(o),0)),'','September 2026','','money','gold')}
 ${kpi('Stok Pakan',num(calc.feedStockTheory()),'kg',`Cukup ${num(calc.feedDaysLeft(),0)} hari`,'','feed')}
 ${kpi('Item di Bawah Minimum',DB.inventory.filter(i=>i.qty<i.min).length,'item','Perlu pembelian','warn','box')}
 ${kpi('Pengeluaran Siklus',rp(calc.modal()),'','Disetujui','','money','gold')}
 ${kpi('Menunggu Approval Owner',calc.pendingApprovals().length,'transaksi','Pembelian & penjualan','','check')}</div>
 <div class="grid g-2" style="margin-top:14px"><div class="card"><div class="card-h"><h3>Order Terbaru</h3><button class="btn primary sm" data-act="modal" data-m="order">${ic('plus',14)} Buat Order</button></div>${ordersTable(DB.orders.slice().sort((a,b)=>b.date-a.date).slice(0,5))}</div>${inventoryCard()}</div>
 <div class="grid g-2" style="margin-top:14px">${chartCard('Biaya per Kategori','ch-cost')}${recentActivity(5)}</div>
 `;}

function popFlow(){const b=calc.popBalance();return `<div class="flow"><div class="n"><b class="num">${num(b.dod)}</b><small>DOD masuk</small></div><span class="op">−</span><div class="n neg"><b class="num">${num(b.mati)}</b><small>Mati</small></div><span class="op">−</span><div class="n neg"><b class="num">${num(b.jual)}</b><small>Terjual</small></div><span class="op">=</span><div class="n res"><b class="num">${num(b.akhir)}</b><small>Ekor tersisa</small></div></div>`;}
function feedStockCard(){const fd=calc.feedDiff();const days=calc.feedDaysLeft();const lastP=DB.feedPurchases.filter(p=>p.status==='APPROVED').slice(-1)[0];return `<div class="card"><div class="card-h"><h3>Stok Pakan</h3><button class="btn ghost sm" data-act="go" data-page="stok">Detail ${ic('arrow',12)}</button></div>
 <div class="row" style="align-items:flex-end;gap:14px"><div><div class="val num" style="font-size:30px;font-weight:800">${num(calc.feedStockTheory())} <small style="font-size:13px;color:var(--muted)">kg</small></div><small style="color:var(--muted)">Stok teoritis (transaksi)</small></div>${fd?`<div>${stBadge(Math.abs(fd.diff)>=10?'OPEN':'VERIFIED')}<div style="font-size:12px;color:var(--muted);margin-top:4px">Opname ${num(fd.op.physical)} kg · selisih <b class="num" style="color:${Math.abs(fd.diff)>=10?'#F2C46B':'inherit'}">${num(fd.diff)} kg</b></div></div>`:''}</div>
 <div class="bar ${days<MASTER.minStokPakanHari?'r':''}" style="margin:12px 0 6px"><i style="width:${Math.min(100,days/20*100)}%"></i></div><div style="font-size:12.5px;color:var(--muted)">Cukup untuk <b style="color:var(--text)">${num(days,0)} hari</b> pada rata-rata ${num(calc.feedAvg7(),0)} kg/hari</div>
 ${lastP?`<div class="alert info" style="margin-top:12px;align-items:center">${ic('truck',16)}<div style="flex:1"><b>Pembelian terakhir</b><small style="color:var(--muted)">${num(lastP.qty)} kg · ${fmtDate(lastP.date)} · ${rp(lastP.qty*lastP.price)}</small></div></div>`:''}</div>`;}
function financeCycleCard(){const c=calc.costByCat();const top=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,4);return `<div class="card"><div class="card-h"><h3>Keuangan Siklus ${DB.cycle.code}</h3><button class="btn ghost sm" data-act="go" data-page="keuangan">Detail ${ic('arrow',12)}</button></div>
 <div class="grid" style="grid-template-columns:1fr 1fr;gap:10px"><div><small style="color:var(--muted)">Total biaya</small><div class="num" style="font-size:22px;font-weight:800;color:#F29390">${rp(calc.modal())}</div></div><div><small style="color:var(--muted)">Estimasi omzet</small><div class="num" style="font-size:22px;font-weight:800;color:var(--soft)">${rp(calc.estRevenue())}</div></div></div>
 <div style="margin:14px 0;padding:14px;border-radius:12px;background:rgba(198,161,91,.1);border:1px solid rgba(198,161,91,.3)"><small style="color:var(--muted)">Estimasi laba</small><div class="row" style="justify-content:space-between"><b class="num" style="font-size:26px;color:var(--gold)">${rp(calc.estProfit())}</b><span class="badge b-gold">ROI ${pct(calc.roi())}</span></div><small style="color:var(--muted)">Omzet − modal berjalan − proyeksi biaya sisa siklus (${rp(calc.projectedRemainingCost())})</small></div>
 <div style="display:flex;flex-direction:column;gap:8px">${top.map(([k,v])=>`<div><div class="row" style="justify-content:space-between;font-size:12.5px"><span>${k}</span><b class="num">${rp(v)}</b></div><div class="bar g"><i style="width:${v/calc.modal()*100}%"></i></div></div>`).join('')}</div></div>`;}
function barnPerfCard(){return `<div class="card"><div class="card-h"><h3>Kinerja per Kandang</h3></div><div class="grid" style="grid-template-columns:1fr 1fr;gap:10px">${['A','B'].map(b=>{const w=calc.avgWeight(b);const m=calc.mortTotal(b);const cond=DB.barnCond.filter(c=>c.barn===b)[0];return `<div class="barn-card"><div class="hd"><b>${barnName(b)}</b>${cond&&cond.litter!=='Kering'?badge('warn','CEK SEKAM'):badge('ok','NORMAL')}</div><div class="kv"><span>Populasi</span><b class="num">${num(calc.population(b))} ekor</b><span>Bobot</span><b class="num">${num(w,2)} kg</b><span>Mati</span><b class="num">${m} ekor</b><span>Pakan hari ini</span><b class="num">${num(DB.feedRecords.filter(r=>r.barn===b&&dayOf(r.date)===calc.day()).reduce((s,r)=>s+calc.feedVal(r),0))} kg</b><span>PIC</span><b>${DB.users.filter(u=>u.barn===b&&u.active).map(u=>u.name.split(' ')[0]).join(', ')}</b></div></div>`;}).join('')}</div><div class="chart-box sm" style="margin-top:12px"><canvas id="ch-barn"></canvas></div></div>`;}
function barnCondCard(){const today=DB.barnCond.filter(c=>dayOf(c.date)===calc.day());return `<div class="card"><div class="card-h"><h3>Kondisi Kandang Hari Ini</h3><span class="sub">Input anak kandang</span></div>${today.length?`<div class="tbl-wrap"><table><thead><tr><th>Kandang</th><th>Suhu</th><th>Kelembapan</th><th>Sekam</th><th>Air</th><th>Catatan</th><th>User</th></tr></thead><tbody>${today.map(c=>`<tr><td><b>${barnName(c.barn)}</b></td><td class="num">${c.temp}°C</td><td class="num">${c.hum}%</td><td>${c.litter==='Kering'?badge('ok',c.litter):badge('warn',c.litter)}</td><td>${badge('ok',c.water)}</td><td style="white-space:normal">${c.note||'—'}</td><td>${userName(c.user).split(' ')[0]}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Belum ada input hari ini','Anak kandang belum mengisi kondisi kandang.')}</div>`;}

function pgSiklus(){const c=DB.cycle;const d=calc.day();const stages=[['DOD masuk',1,1],['Brooding',1,14],['Growing',15,35],['Finishing',36,44],['Panen',45,45]];const active=state.tab||'aktif';
 return pageHead('Siklus Ternak','Setiap siklus adalah unit akuntansi tersendiri: DOD, biaya, populasi, dan hasil panen terikat ke siklus.',(can('masterData')?`<button class="btn primary" data-act="modal" data-m="cycle">${ic('plus',14)} Siklus Baru</button>`:''))+
 `<div class="tabs"><button class="${active==='aktif'?'active':''}" data-act="tab" data-v="aktif">Siklus Aktif</button><button class="${active==='riwayat'?'active':''}" data-act="tab" data-v="riwayat">Riwayat Siklus</button></div>`+
 (active==='riwayat'?`<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Siklus</th><th>Jenis</th><th>DOD</th><th>Tanggal DOD</th><th>Panen</th><th>Ekor panen</th><th>Bobot</th><th>FCR</th><th>Mortalitas</th>${can('finance')?'<th class="r">Omzet</th><th class="r">Laba</th>':''}<th>Status</th></tr></thead><tbody>
  <tr><td><b>${c.code}</b></td><td>${c.breed}</td><td class="num">${c.dodQty}</td><td>${fmtDate(c.dodDate)}</td><td>${fmtDate(dateOfDay(c.targetDays))} (est.)</td><td class="num">${num(calc.projectedPop())} (est.)</td><td class="num">${num(calc.avgWeight(),2)} kg</td><td class="num">${calc.fcr()?num(calc.fcr().fcr,2):'—'}</td><td class="num">${pct(calc.mortPct())}</td>${can('finance')?`<td class="r num">${rp(calc.estRevenue())}</td><td class="r num">${rp(calc.estProfit())}</td>`:''}<td>${stBadge('AKTIF')}</td></tr>
  ${DB.prevCycles.map(p=>`<tr><td><b>${p.code}</b></td><td>${p.breed}</td><td class="num">${p.dodQty}</td><td>${fmtDate(p.dodDate)}</td><td colspan="${can('finance')?7:5}" style="color:var(--dim)">Ringkasan siklus lama tersedia di Laporan Siklus</td><td>${stBadge('SELESAI')}</td></tr>`).join('')}</tbody></table></div></div>`:
 `<div class="grid g-2"><div class="card"><div class="card-h"><h3>Siklus ${c.code} · ${c.breed}</h3>${stBadge(c.status)}</div><div class="kv" style="grid-template-columns:auto 1fr;row-gap:10px"><span>Tanggal DOD</span><b>${fmtLong(c.dodDate)}</b><span>Jumlah DOD</span><b class="num">${num(c.dodQty)} ekor</b><span>Harga DOD</span><b class="num">${rp(c.dodPrice)}/ekor <small style="color:var(--muted)">(master data)</small></b><span>Modal DOD</span><b class="num">${rp(c.dodQty*c.dodPrice)}</b><span>Target panen</span><b>${c.targetDays} hari · ${fmtLong(dateOfDay(c.targetDays))}</b><span>Target bobot</span><b class="num">${num(c.targetWeight[0],1)}–${num(c.targetWeight[1],1)} kg</b><span>Target mortalitas</span><b>&lt; ${c.targetMort}%</b><span>Kandang</span><b>Kandang A (${num(calc.population('A'))} ekor), Kandang B (${num(calc.population('B'))} ekor)</b><span>Dibuat oleh</span><b>${userName(c.createdBy)} · ${fmtDT(c.createdAt||c.dodDate)} ${badge('neutral','TERKUNCI')}</b></div>
  <div class="alert info" style="margin-top:14px">${ic('lock',16)}<div><b>Jumlah & harga DOD terkunci</b>Perubahan hanya lewat "Ajukan Koreksi" dengan bukti surat jalan dan persetujuan Owner.</div></div></div>
  <div class="card"><div class="card-h"><h3>Timeline Siklus</h3><span class="sub">Hari ke-${d} dari ${c.targetDays}</span></div><div class="stage">${stages.map(([n,s,e])=>`<div class="${d>e?'done':d>=s?'now':''}">${n}<small>H${s}${e>s?'–'+e:''}</small></div>`).join('')}</div>
  <div class="timeline" style="margin-top:18px">${[['DOD masuk','done',fmtDT(c.dodDate),`${num(c.dodQty)} ekor DOD — ${userName(c.createdBy)}`],['Brooding selesai','done',fmtDate(dateOfDay(14)),'Pemanas dilepas, mortalitas brooding 8 ekor (1,6%)'],['Growing (fase sekarang)','now',`H15–H35`,`Bobot ${num(calc.avgWeight(),2)} kg · target H${d} ${num(calc.target(d),2)} kg`],['Finishing','todo',fmtDate(dateOfDay(36)),'Pakan finisher, seleksi bobot untuk pre-order'],['Panen','todo',fmtDate(dateOfDay(45)),`Estimasi ${num(calc.projectedPop())} ekor · ~${num(MASTER.targetBobotMin*1.1,2)} kg`]].map(([b,k,t,dd])=>`<div class="tl ${k}"><div class="t">${t}</div><div class="b">${b}</div><div class="d">${dd}</div></div>`).join('')}</div></div></div>
  <div class="grid g-3" style="margin-top:14px">${kpi('Populasi',num(calc.population()),'ekor',`${calc.mortTotal()} mati · ${calc.popBalance().jual} terjual`,'','duck')}${kpi('Bobot rata-rata',num(calc.avgWeight(),2),'kg',`Target H${d}: ${num(calc.target(d),2)} kg`,'','scale')}${kpi('Pakan kumulatif',num(calc.feedTotal()),'kg',`FCR ${calc.fcr()?num(calc.fcr().fcr,2):'—'}`,'','feed')}</div>`);}

function pgPopulasi(){const b=calc.popBalance();const tab=state.tab||'ledger';
 return pageHead('Populasi & Mortalitas','Populasi tidak pernah diubah langsung. Setiap angka berasal dari transaksi: DOD masuk, transfer, kematian, penjualan.',`${seg([['ALL','Semua'],['A','Kandang A'],['B','Kandang B']],state.barn,'barn')}`)+
 `<div class="card" style="margin-bottom:14px"><div class="card-h"><h3>Balance Populasi ${state.barn==='ALL'?'':'· '+barnName(state.barn)}</h3></div>
  <div class="flow"><div class="n"><b class="num">${num(state.barn==='ALL'?b.dod:250)}</b><small>Populasi awal (DOD)</small></div><span class="op">+</span><div class="n"><b class="num">${b.tIn}</b><small>Transfer masuk</small></div><span class="op">−</span><div class="n neg"><b class="num">${calc.mortTotal(state.barn==='ALL'?null:state.barn)}</b><small>Kematian</small></div><span class="op">−</span><div class="n neg"><b class="num">${DB.popTx.filter(t=>t.type==='PENJUALAN'&&(state.barn==='ALL'||t.barn===state.barn)).reduce((s,t)=>s-t.qty,0)}</b><small>Penjualan</small></div><span class="op">−</span><div class="n neg"><b class="num">${b.tOut}</b><small>Transfer keluar</small></div><span class="op">=</span><div class="n res"><b class="num">${num(calc.population(state.barn==='ALL'?null:state.barn))}</b><small>Populasi akhir</small></div></div>
  <div class="alert ok" style="margin-top:14px">${ic('check',16)}<div><b>Balance OK</b>Jumlah transaksi sama dengan populasi akhir. Mortalitas kumulatif ${pct(calc.mortPct())} (target &lt; ${MASTER.targetMortalitasPct}%).</div></div></div>
 <div class="grid g-2" style="margin-bottom:14px">${chartCard('Populasi Harian','ch-pop',rangeSeg())}${chartCard('Mortalitas Harian','ch-mort','','', 'Batas normal '+MASTER.batasMortalitasHarian+' ekor/hari')}</div>
 <div class="tabs"><button class="${tab==='ledger'?'active':''}" data-act="tab" data-v="ledger">Ledger Transaksi</button><button class="${tab==='mort'?'active':''}" data-act="tab" data-v="mort">Catatan Kematian</button></div>
 ${tab==='ledger'?`<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Waktu</th><th>Jenis</th><th>Kandang</th><th class="r">Jumlah</th><th class="r">Saldo</th><th>Referensi</th><th>User</th><th>Status</th></tr></thead><tbody>${(()=>{let run=0;return DB.popTx.filter(t=>state.barn==='ALL'||t.barn===state.barn).slice().sort((a,b)=>a.date-b.date).map(t=>{run+=t.qty;return `<tr><td class="num">${fmtDT(t.date)}</td><td>${badge(t.qty>0?'ok':'danger',t.type.replace('_',' '))}</td><td>${barnName(t.barn)}</td><td class="r num" style="color:${t.qty>0?'var(--soft)':'#F29390'}">${t.qty>0?'+':''}${t.qty}</td><td class="r num"><b>${run}</b></td><td><code style="font-size:11px">${t.ref}</code></td><td>${userName(t.user)}</td><td>${t.locked?badge('neutral','TERKUNCI'):stBadge('RECORDED')}</td></tr>`;}).reverse().join('');})()}</tbody></table></div></div>`:
 `<div class="card"><div class="card-h"><h3>Catatan Kematian</h3>${state.user.role!=='ANAK_KANDANG'?`<button class="btn sm" data-act="modal" data-m="mort">${ic('plus',14)} Catat kematian</button>`:''}</div><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th>Kandang</th><th class="r">Jumlah</th><th>Penyebab</th><th>Bukti</th><th>User</th><th>Status</th><th></th></tr></thead><tbody>${DB.mortality.filter(m=>state.barn==='ALL'||m.barn===state.barn).slice().reverse().map(m=>`<tr><td class="num">${fmtDT(m.date)}</td><td>${barnName(m.barn)}</td><td class="r num"><b>${m.qty}</b>${m.qty>=MASTER.batasMortalitasHarian?' '+badge('warn','WARNING'):''}</td><td>${m.cause}</td><td>${photoChip(m.photo)}</td><td>${userName(m.user)}</td><td>${m.locked?badge('neutral','TERKUNCI'):stBadge(m.status)}</td><td><button class="btn ghost sm" data-act="modal" data-m="correction" data-type="MORT" data-id="${m.id}">Ajukan koreksi</button></td></tr>`).join('')}</tbody></table></div></div>`}
 `;}

function feedVersions(r){if(!r.versions.length)return '';return `<div style="margin-top:6px">${r.versions.map((v,i)=>`<div class="ver ${i===r.versions.length-1?'active':''}"><s>${i===0?r.kg:r.versions[i-1].kg} kg</s> → <b>${v.kg} kg</b> · ${v.reason} · disetujui ${userName(v.approvedBy)} ${fmtDT(v.date)}</div>`).join('')}</div>`;}
function pgPakan(){const fd=calc.feedDiff();const tab=state.tab||'riwayat';const purchased=calc.feedPurchased();
 return pageHead('Pakan','Stok pakan dihitung dari transaksi: pembelian − pemakaian ± penyesuaian. Selisih dengan opname fisik selalu ditampilkan.',`${state.user.role!=='ANAK_KANDANG'?`<button class="btn" data-act="modal" data-m="opname">${ic('scale',14)} Stock Opname</button>`:''}${can('inputPurchase')||can('masterData')?`<button class="btn primary" data-act="modal" data-m="purchase">${ic('plus',14)} Pembelian Pakan</button>`:''}`)+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Stok Awal Siklus','0','kg','Siklus #000 habis terpakai','','box')}${kpi('Pembelian',num(purchased),'kg',`${DB.feedPurchases.filter(p=>p.status==='APPROVED').length} transaksi disetujui`,'','truck')}${kpi('Pemakaian',num(calc.feedTotal()),'kg',`Rata-rata ${num(calc.feedAvg7(),0)} kg/hari (7 hari)`,'','feed')}${kpi('Penyesuaian',num(calc.feedAdjusted()),'kg',DB.feedAdjust.length?'Disetujui':'Belum ada','','pen')}${kpi('Stok Teoritis',num(calc.feedStockTheory()),'kg',`Cukup ${num(calc.feedDaysLeft(),0)} hari`,calc.feedDaysLeft()<MASTER.minStokPakanHari?'down':'up','box','gold')}${fd?kpi('Stok Fisik (Opname)',num(fd.op.physical),'kg',`Selisih ${num(fd.diff)} kg · ${fmtDate(fd.op.date)}`,Math.abs(fd.diff)>=10?'warn':'up','scale',Math.abs(fd.diff)>=10?'red':''):''}</div>
 ${fd&&Math.abs(fd.diff)>=10?`<div class="alert warn" style="margin-bottom:14px">${ic('alert',18)}<div style="flex:1"><b>Selisih stok pakan ${num(Math.abs(fd.diff))} kg — PERLU VERIFIKASI</b>Stok teoritis per ${fmtDT(fd.op.date)} adalah ${num(fd.theory)} kg, opname fisik ${num(fd.op.physical)} kg. Selisih ini bukan tuduhan; bisa berasal dari tumpahan, karung tidak penuh, atau input yang belum tercatat. Verifikasi lalu ajukan penyesuaian stok dengan bukti.</div>${can('approve')?`<button class="btn sm" data-act="modal" data-m="adjust">Ajukan penyesuaian</button>`:''}</div>`:''}
 <div class="grid g-2" style="margin-bottom:14px">${chartCard('Konsumsi Pakan Harian','ch-feed',rangeSeg(),'','Hari ini '+num(calc.feedToday())+' kg vs rata-rata 7 hari '+num(calc.feedAvg7(),1)+' kg')}<div class="card"><div class="card-h"><h3>FCR Transparan</h3></div>${(()=>{const f=calc.fcr();return f?`<div class="kv" style="row-gap:10px"><span>Total pakan</span><b class="num">${num(f.feed)} kg</b><span>Biomassa sekarang</span><b class="num">${num(calc.population())} ekor × ${num(calc.avgWeight(),2)} kg = ${num(calc.population()*calc.avgWeight(),1)} kg</b><span>Biomassa awal (DOD)</span><b class="num">${DB.cycle.dodQty} × ${MASTER.targetCurve[0][1]} kg = ${num(DB.cycle.dodQty*MASTER.targetCurve[0][1],1)} kg</b><span>Pertambahan biomassa</span><b class="num">${num(f.bio,1)} kg</b><span>FCR</span><b class="num" style="font-size:22px;color:var(--gold)">${num(f.feed)} ÷ ${num(f.bio,1)} = ${num(f.fcr,2)}</b></div><div class="chart-box sm" style="margin-top:10px"><canvas id="ch-fcr"></canvas></div>`:'<div class="alert info">Data belum cukup untuk menghitung FCR.</div>';})()}</div></div>
 <div class="tabs"><button class="${tab==='riwayat'?'active':''}" data-act="tab" data-v="riwayat">Riwayat Pemakaian</button><button class="${tab==='beli'?'active':''}" data-act="tab" data-v="beli">Pembelian</button><button class="${tab==='opname'?'active':''}" data-act="tab" data-v="opname">Opname & Penyesuaian</button></div>
 ${tab==='riwayat'?`<div class="card"><div class="card-h"><h3>Riwayat Input Pakan</h3>${seg([['ALL','Semua'],['A','Kandang A'],['B','Kandang B']],state.barn,'barn')}</div><div class="tbl-wrap"><table><thead><tr><th>Waktu</th><th>Kandang</th><th class="r">Jumlah</th><th>Bukti</th><th>User</th><th>Status</th><th></th></tr></thead><tbody>${DB.feedRecords.filter(r=>state.barn==='ALL'||r.barn===state.barn).slice(-16).reverse().map(r=>`<tr><td class="num">${fmtDT(r.date)}</td><td>${barnName(r.barn)}</td><td class="r num"><b>${calc.feedVal(r)} kg</b>${r.versions.length?' '+badge('info','V'+(r.versions.length+1)):''}${feedVersions(r)}</td><td>${photoChip(r.photo)}</td><td>${userName(r.user)}</td><td>${DB.corrections.find(c=>c.recordId===r.id&&c.status==='PENDING')?badge('pending','KOREKSI MENUNGGU'):r.locked?badge('neutral','TERKUNCI'):stBadge(r.status)}</td><td><button class="btn ghost sm" data-act="modal" data-m="correction" data-type="FEED" data-id="${r.id}">Ajukan koreksi</button></td></tr>`).join('')}</tbody></table></div></div>`:
 tab==='beli'?`<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th class="r">Jumlah</th><th class="r">Harga/kg</th><th class="r">Total</th><th>Vendor</th><th>No. Bukti</th><th>Nota</th><th>User</th><th>Status</th></tr></thead><tbody>${DB.feedPurchases.slice().reverse().map(p=>`<tr><td>${fmtDate(p.date)}</td><td class="r num">${num(p.qty)} kg</td><td class="r num">${p.price?rp(p.price):'—'}</td><td class="r num"><b>${p.price?rp(p.qty*p.price):'—'}</b></td><td>${p.vendor}</td><td><code style="font-size:11px">${p.ref}</code></td><td>${photoChip('nota')}</td><td>${userName(p.user)}</td><td>${stBadge(p.status)}</td></tr>`).join('')}</tbody></table></div></div>`:
 `<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th>Jenis</th><th class="r">Teoritis</th><th class="r">Fisik / Qty</th><th class="r">Selisih</th><th>Catatan</th><th>User</th><th>Status</th></tr></thead><tbody>${DB.feedOpname.map(o=>{const t=calc.feedStockAtDate(o.date);return `<tr><td class="num">${fmtDT(o.date)}</td><td>${badge('info','OPNAME')}</td><td class="r num">${num(t)} kg</td><td class="r num">${num(o.physical)} kg</td><td class="r num" style="color:${Math.abs(t-o.physical)>=10?'#F2C46B':'var(--soft)'}"><b>${num(t-o.physical)} kg</b></td><td>${o.note}</td><td>${userName(o.user)}</td><td>${Math.abs(t-o.physical)>=10?stBadge('OPEN'):stBadge('VERIFIED')}</td></tr>`;}).join('')}${DB.feedAdjust.map(a=>`<tr><td class="num">${fmtDT(a.date)}</td><td>${badge('gold','PENYESUAIAN')}</td><td class="r">—</td><td class="r num">${a.qty>0?'+':''}${num(a.qty)} kg</td><td class="r">—</td><td>${a.reason}</td><td>${userName(a.user)}</td><td>${stBadge('APPROVED')}</td></tr>`).join('')}</tbody></table></div></div>`}
 `;}

function pgPertumbuhan(){const gap=calc.weightGap();const d=calc.day();
 return pageHead('Pertumbuhan','Bobot rata-rata dihitung dari sampel timbang (total berat ÷ jumlah sampel), dibandingkan dengan kurva target Peking.',state.user.role!=='ANAK_KANDANG'?`<button class="btn primary" data-act="modal" data-m="weigh">${ic('scale',14)} Input Timbang</button>`:'')+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Bobot Rata-rata',num(calc.avgWeight(),2),'kg',`Sampel terakhir ${fmtDate(DB.weights.slice(-1)[0].date)}`,'','scale')}${kpi('Target Hari ke-'+d,num(calc.target(d),2),'kg',`${gap>=0?'+':''}${num(gap,1)}% vs target`,gap<-3?'warn':'up','growth')}${kpi('Target Panen',num(MASTER.targetBobotMin,1)+'–'+num(MASTER.targetBobotMax,1),'kg',`H${DB.cycle.targetDays} · ${fmtDate(dateOfDay(DB.cycle.targetDays))}`,'','duck')}${kpi('ADG 7 hari terakhir',num((DB.weights.slice(-1)[0].avg-DB.weights.slice(-3)[0].avg)/(dayOf(DB.weights.slice(-1)[0].date)-dayOf(DB.weights.slice(-3)[0].date))*1000,0),'g/hari','Pertambahan bobot harian','','growth')}${kpi('FCR',calc.fcr()?num(calc.fcr().fcr,2):'—','','Transparan · lihat halaman Pakan','','feed')}</div>
 ${gap<-3?`<div class="alert warn" style="margin-bottom:14px">${ic('alert',18)}<div><b>Bobot tertinggal ${num(Math.abs(gap))}% dari kurva target</b>Periksa kualitas pakan, kepadatan kandang, dan suhu. Rekomendasi: timbang ulang sampel 30 ekor per kandang besok pagi.</div></div>`:''}
 <div class="grid g-2" style="margin-bottom:14px">${chartCard('Aktual vs Target','ch-weight','','','kg · seluruh siklus')}${chartCard('Perbandingan Kandang','ch-barn','','','bobot rata-rata terakhir')}</div>
 <div class="card"><div class="card-h"><h3>Riwayat Timbang</h3></div><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th>Hari</th><th>Kandang</th><th class="r">Sampel</th><th class="r">Total berat</th><th class="r">Rata-rata</th><th class="r">Target</th><th>Foto timbangan</th><th>User</th><th>Status</th><th></th></tr></thead><tbody>${DB.weights.slice().reverse().map(w=>{const dd=dayOf(w.date);const t=calc.target(dd);return `<tr><td>${fmtDate(w.date)}</td><td class="num">H${dd}</td><td>${barnName(w.barn)}</td><td class="r num">${w.n} ekor</td><td class="r num">${num(w.total,1)} kg</td><td class="r num"><b>${num(w.avg,2)} kg</b></td><td class="r num" style="color:${w.avg<t*0.97?'#F2C46B':'var(--soft)'}">${num(t,2)} kg</td><td>${photoChip(w.photo)}</td><td>${userName(w.user)}</td><td>${w.locked?badge('neutral','TERKUNCI'):stBadge('RECORDED')}</td><td><button class="btn ghost sm" data-act="modal" data-m="correction" data-type="WEIGHT" data-id="${w.id}">Ajukan koreksi</button></td></tr>`;}).join('')}</tbody></table></div></div>
 `;}

function pgKesehatan(){const list=DB.health.filter(h=>state.barn==='ALL'||h.barn===state.barn||h.barn==='ALL');
 return pageHead('Kesehatan','Vaksinasi, vitamin, pengobatan, dan observasi. Setiap tindakan tercatat dengan dosis, user, dan waktu.',`${seg([['ALL','Semua'],['A','Kandang A'],['B','Kandang B'],['C','Kandang C']],state.barn,'barn')}${state.user.role!=='ANAK_KANDANG'?`<button class="btn primary" data-act="modal" data-m="health">${ic('plus',14)} Catat Tindakan</button>`:''}`)+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Status Kesehatan','NORMAL','','Tidak ada isolasi aktif','up','heart')}${kpi('Vaksinasi','1','program','AI H5N1 · H3 ✓','','shield')}${kpi('Vitamin','2','pemberian','Terakhir H14 · jadwal H21 terlewat','warn','leaf')}${kpi('Pengobatan','1','kasus','Kandang B · H22–H25 · selesai','','heart')}</div>
 ${state.barn==='C'?emptyState('Belum ada catatan kesehatan','Kandang C kosong. Catatan akan muncul saat kandang terisi.'):`<div class="grid g-2"><div class="card"><div class="card-h"><h3>Riwayat Tindakan</h3></div><div class="timeline">${list.slice().reverse().map(h=>`<div class="tl ${h.type==='Pengobatan'?'now':'done'}"><div class="t">${fmtDT(h.date)} · ${barnName(h.barn)}</div><div class="b">${badge(h.type==='Pengobatan'?'warn':h.type==='Vaksinasi'?'ok':'info',h.type.toUpperCase())} ${h.item}</div><div class="d">Dosis: ${h.dose}${h.note?' · '+h.note:''} · oleh ${userName(h.user)}</div></div>`).join('')}</div></div>
 <div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="card-h"><h3>Jadwal Program Kesehatan</h3></div><div class="tbl-wrap"><table><thead><tr><th>Hari</th><th>Program</th><th>Status</th></tr></thead><tbody>${[[3,'Vaksin AI H5N1','APPROVED'],[7,'Vitamin (3 hari)','APPROVED'],[14,'Vitamin','APPROVED'],[21,'Vitamin','MISSED'],[28,'Vitamin + elektrolit','APPROVED'],[35,'Vitamin','PLAN'],[42,'Puasa obat (withdrawal)','PLAN']].map(([d,p,s])=>`<tr><td class="num">H${d}</td><td>${p}</td><td>${s==='APPROVED'?badge('ok','SELESAI'):s==='MISSED'?badge('warn','TERLEWAT'):badge('neutral','TERJADWAL')}</td></tr>`).join('')}</tbody></table></div></div>${barnCondCard()}</div></div>`}`;}

function pgKeuangan(){if(!can('finance'))return denied();const c=calc.costByCat();const tab=state.tab||'biaya';
 return pageHead('Keuangan','Semua biaya terikat ke siklus dengan vendor, nomor bukti, foto nota, dan status approval.',`<button class="btn" data-act="export" data-what="Laporan Keuangan">${ic('dl',14)} Export</button><button class="btn primary" data-act="modal" data-m="expense">${ic('plus',14)} Catat Biaya</button>`)+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Modal Berjalan',rp(calc.modal()),'','Biaya disetujui siklus #001','','money','gold')}${kpi('Omzet Realisasi',rp(DB.orders.filter(o=>o.pay==='PAID').reduce((s,o)=>s+calc.orderTotal(o),0)),'','Penjualan dibayar (produk siklus #000)','','cart','gold')}${kpi('Estimasi Omzet Panen',rp(calc.estRevenue()),'',`${num(calc.projectedPop())} ekor × ~${num(MASTER.targetBobotMin*1.1,2)} kg × ${rp(MASTER.hargaJualHidupKg)}/kg`,'','growth','gold')}${kpi('Estimasi Laba',rp(calc.estProfit()),'',`ROI ${pct(calc.roi())} · HPP ${rp((calc.modal()+calc.projectedRemainingCost())/calc.projectedPop())}/ekor`,calc.estProfit()>0?'up':'down','money','gold')}</div>
 <div class="grid g-2" style="margin-bottom:14px">${chartCard('Biaya per Kategori','ch-cost')}${chartCard('Biaya, Omzet & Proyeksi Laba','ch-fin',rangeSeg(),'','kumulatif')}</div>
 <div class="tabs"><button class="${tab==='biaya'?'active':''}" data-act="tab" data-v="biaya">Daftar Biaya</button><button class="${tab==='laba'?'active':''}" data-act="tab" data-v="laba">Proyeksi Laba Rugi</button></div>
 ${tab==='biaya'?`<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th>Kategori</th><th class="r">Nominal</th><th>Vendor</th><th>No. Bukti</th><th>Nota</th><th>User</th><th>Status</th></tr></thead><tbody>${[...DB.expenses.map(e=>({...e,kind:'E'})),...DB.feedPurchases.map(p=>({id:p.id,date:p.date,cat:'Pakan',amount:p.qty*p.price,vendor:p.vendor,ref:p.ref,user:p.user,status:p.status,kind:'P'}))].sort((a,b)=>b.date-a.date).map(e=>`<tr><td>${fmtDate(e.date)}</td><td>${badge(e.cat==='DOD'?'gold':e.cat==='Pakan'?'ok':'info',e.cat.toUpperCase())}</td><td class="r num"><b>${rp(e.amount)}</b></td><td>${e.vendor}</td><td><code style="font-size:11px">${e.ref}</code></td><td>${photoChip('nota')}</td><td>${userName(e.user)}</td><td>${stBadge(e.status)}</td></tr>`).join('')}</tbody></table></div></div>`:
 `<div class="card"><div class="card-h"><h3>Proyeksi Laba Rugi Siklus ${DB.cycle.code}</h3></div><div class="tbl-wrap"><table><tbody>${Object.entries(c).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<tr><td>Biaya ${k}</td><td class="r num">${rp(v)}</td><td class="r num" style="color:var(--dim)">${pct(v/calc.modal()*100)}</td></tr>`).join('')}<tr style="background:rgba(255,255,255,.04)"><td><b>Total modal berjalan</b></td><td class="r num"><b>${rp(calc.modal())}</b></td><td></td></tr><tr><td>Proyeksi biaya sisa siklus (${DB.cycle.targetDays-calc.day()} hari)</td><td class="r num">${rp(calc.projectedRemainingCost())}</td><td></td></tr><tr><td>Estimasi omzet panen</td><td class="r num" style="color:var(--soft)">${rp(calc.estRevenue())}</td><td></td></tr><tr style="background:rgba(198,161,91,.1)"><td><b>Estimasi laba</b></td><td class="r num"><b style="color:var(--gold);font-size:16px">${rp(calc.estProfit())}</b></td><td class="r num">ROI ${pct(calc.roi())}</td></tr></tbody></table></div><p style="color:var(--muted);font-size:12px;margin-top:10px">Asumsi: harga jual hidup ${rp(MASTER.hargaJualHidupKg)}/kg, bobot panen ~${num(MASTER.targetBobotMin*1.1,2)} kg, mortalitas berlanjut pada laju saat ini. Semua asumsi dapat diubah di Pengaturan → Master Data.</p></div>`}
 `;}

function ordersTable(list){return list.length?`<div class="tbl-wrap"><table><thead><tr><th>No. Order</th><th>Tanggal</th><th>Customer</th><th>Produk</th><th class="r">Jumlah</th><th class="r">Berat</th>${can('finance')?'<th class="r">Total</th>':''}<th>Bayar</th><th>Kirim</th><th>Status</th><th>Sumber</th><th></th></tr></thead><tbody>${list.map(o=>{const p=DB.products.find(x=>x.id===o.product);const cu=DB.customers.find(x=>x.id===o.customer);return `<tr><td><b>${o.id}</b></td><td class="num">${fmtDT(o.date)}</td><td>${cu.name}<br><small style="color:var(--dim)">${cu.phone}</small></td><td>${p.name.replace('Bebek Peking ','')}</td><td class="r num">${o.qty} ekor</td><td class="r num">${o.weight?num(o.weight,1)+' kg':'<span style="color:var(--dim)">est. '+num(o.qty*p.avgW,1)+' kg</span>'}</td>${can('finance')?`<td class="r num"><b>${rp(calc.orderTotal(o))}</b></td>`:''}<td>${stBadge(o.pay)}</td><td>${stBadge(o.ship)}</td><td>${stBadge(o.status)}</td><td>${badge(o.source==='WEBSITE'?'gold':'neutral',o.source)}</td><td>${o.status==='NEW'&&(can('inputSales')||can('approve'))?`<button class="btn primary sm" data-act="order-status" data-id="${o.id}" data-s="CONFIRMED">Konfirmasi</button>`:o.status==='CONFIRMED'&&(can('inputSales')||can('approve'))?`<button class="btn sm" data-act="order-status" data-id="${o.id}" data-s="PAID">Tandai dibayar</button>`:o.status==='PAID'&&(can('inputSales')||can('approve'))?`<button class="btn sm" data-act="order-status" data-id="${o.id}" data-s="DELIVERED">Tandai terkirim</button>`:''}</td></tr>`;}).join('')}</tbody></table></div>`:emptyState('Belum ada order','Order dari admin atau website akan tampil di sini.');}
function pgPenjualan(){const tab=state.tab||'order';const paid=DB.orders.filter(o=>o.pay==='PAID');
 return pageHead('Penjualan','Order mengurangi stok secara otomatis saat dikonfirmasi. Order dari website masuk dengan status BARU.',`${can('inputSales')||can('approve')?`<button class="btn primary" data-act="modal" data-m="order">${ic('plus',14)} Buat Order</button>`:''}`)+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Order Bulan Ini',DB.orders.filter(o=>o.date>=D(9,1)).length,'order',`${DB.orders.filter(o=>o.status==='NEW').length} baru dari website`,'','cart')}${can('finance')?kpi('Omzet Dibayar',rp(paid.reduce((s,o)=>s+calc.orderTotal(o),0)),'',`${paid.length} order lunas`,'','money','gold'):''}${kpi('Menunggu Approval',DB.orders.filter(o=>o.status==='PENDING_APPROVAL').length,'order','Owner/Manager','','check')}${kpi('Stok Karkas',num(calc.productStock(DB.products[2])),'ekor','Frozen · siklus #000','','box')}${kpi('Stok Potong',num(calc.productStock(DB.products[1])),'ekor',calc.productStock(DB.products[1])<=DB.products[1].minOrder*2?'Stok terbatas':'Tersedia',calc.productStock(DB.products[1])<=DB.products[1].minOrder*2?'warn':'','box')}</div>
 <div class="tabs"><button class="${tab==='order'?'active':''}" data-act="tab" data-v="order">Order</button><button class="${tab==='produk'?'active':''}" data-act="tab" data-v="produk">Produk & Harga</button><button class="${tab==='customer'?'active':''}" data-act="tab" data-v="customer">Customer</button></div>
 ${tab==='order'?`<div class="card"><div class="card-h"><h3>Daftar Order</h3>${seg([['ALL','Semua'],['NEW','Baru'],['PENDING_APPROVAL','Approval'],['DELIVERED','Selesai']],state.filters.os||'ALL','ofilter')}</div>${ordersTable(DB.orders.filter(o=>!state.filters.os||state.filters.os==='ALL'||o.status===state.filters.os).slice().sort((a,b)=>b.date-a.date))}</div>`:
 tab==='produk'?`<div class="grid g-3">${DB.products.map(p=>{const st=calc.stockStatus(p);return `<div class="card"><div class="card-h"><h3>${p.name}</h3>${badge(st.k==='ok'?'ok':st.k==='low'?'warn':st.k==='out'?'danger':'gold',st.t)}</div><p style="color:var(--muted);font-size:13px">${p.desc}</p><div class="kv" style="margin-top:12px">${can('finance')||can('inputSales')?`<span>Harga</span><b class="num">${rp(MASTER[p.priceKg])}/kg</b>`:''}<span>Bobot rata-rata</span><b class="num">${num(p.avgW,2)} kg</b><span>Stok tersedia</span><b class="num">${num(calc.productStock(p))} ${p.unit}</b><span>Minimum order</span><b class="num">${p.minOrder} ${p.unit}</b><span>Sumber stok</span><b>${p.stockFrom==='population'?'Populasi aktif siklus #001':'Inventory '+p.stockFrom}</b></div></div>`;}).join('')}</div>`:
 `<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Customer</th><th>Tipe</th><th>WhatsApp</th><th class="r">Order</th>${can('finance')?'<th class="r">Total belanja</th>':''}</tr></thead><tbody>${DB.customers.map(c=>{const os=DB.orders.filter(o=>o.customer===c.id);return `<tr><td><b>${c.name}</b></td><td>${badge('info',c.type)}</td><td class="num">${c.phone}</td><td class="r num">${os.length}</td>${can('finance')?`<td class="r num">${rp(os.filter(o=>o.pay==='PAID').reduce((s,o)=>s+calc.orderTotal(o),0))}</td>`:''}</tr>`;}).join('')}</tbody></table></div></div>`}`;}

function inventoryCard(){return `<div class="card"><div class="card-h"><h3>Stok Gudang</h3><button class="btn ghost sm" data-act="go" data-page="stok">Detail ${ic('arrow',12)}</button></div><div class="tbl-wrap"><table><thead><tr><th>Item</th><th class="r">Stok</th><th class="r">Min</th><th>Status</th></tr></thead><tbody><tr><td>Pakan</td><td class="r num"><b>${num(calc.feedStockTheory())} kg</b></td><td class="r num">${num(calc.feedAvg7()*MASTER.minStokPakanHari,0)} kg</td><td>${calc.feedDaysLeft()<MASTER.minStokPakanHari?badge('danger','KRITIS'):badge('ok','AMAN')}</td></tr>${DB.inventory.map(i=>`<tr><td>${i.name}</td><td class="r num"><b>${num(i.qty)} ${i.unit}</b></td><td class="r num">${num(i.min)}</td><td>${i.qty<i.min?badge('warn','DI BAWAH MIN'):badge('ok','AMAN')}</td></tr>`).join('')}</tbody></table></div></div>`;}
function pgStok(){const fd=calc.feedDiff();const tab=state.tab||'stok';
 return pageHead('Stok & Gudang','Pakan, vitamin, obat, sekam, peralatan, dan produk panen. Setiap pergerakan stok tercatat sebagai transaksi.',`<button class="btn" data-act="modal" data-m="opname">${ic('scale',14)} Stock Opname</button>${can('masterData')?`<button class="btn primary" data-act="modal" data-m="invin">${ic('plus',14)} Barang Masuk</button>`:''}`)+
 `${calc.feedDaysLeft()<MASTER.minStokPakanHari?`<div class="alert danger" style="margin-bottom:14px">${ic('alert',18)}<div><b>Stok pakan tersisa ${num(calc.feedDaysLeft(),0)} hari</b>Segera ajukan pembelian.</div></div>`:''}
 ${DB.inventory.filter(i=>i.qty<i.min).map(i=>`<div class="alert warn" style="margin-bottom:14px">${ic('alert',18)}<div><b>Stok ${i.name} di bawah minimum</b>${num(i.qty)} ${i.unit} tersisa, minimum ${num(i.min)} ${i.unit}.</div></div>`).join('')}
 <div class="tabs"><button class="${tab==='stok'?'active':''}" data-act="tab" data-v="stok">Stok</button><button class="${tab==='mov'?'active':''}" data-act="tab" data-v="mov">Stock Movement</button><button class="${tab==='opname'?'active':''}" data-act="tab" data-v="opname">Opname & Selisih</button></div>
 ${tab==='stok'?`<div class="grid g-3">${[{name:'Pakan',unit:'kg',cat:'Pakan',qty:calc.feedStockTheory(),min:Math.round(calc.feedAvg7()*MASTER.minStokPakanHari),feed:true},...DB.inventory].map(i=>`<div class="card"><div class="card-h"><div><span class="badge b-neutral">${i.cat.toUpperCase()}</span><h3 style="margin-top:6px">${i.name}</h3></div>${i.qty<i.min?badge('warn','DI BAWAH MIN'):badge('ok','AMAN')}</div><div class="val num" style="font-size:30px;font-weight:800">${num(i.qty)} <small style="font-size:13px;color:var(--muted)">${i.unit}</small></div><div class="bar ${i.qty<i.min?'w':''}" style="margin:10px 0 6px"><i style="width:${Math.min(100,i.qty/(i.min*2.5)*100)}%"></i></div><small style="color:var(--muted)">Minimum ${num(i.min)} ${i.unit}${i.feed?` · cukup ${num(calc.feedDaysLeft(),0)} hari`:''}${fd&&i.feed?` · opname ${num(fd.op.physical)} kg (selisih ${num(fd.diff)} kg)`:''}</small></div>`).join('')}</div>`:
 tab==='mov'?`<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Waktu</th><th>Item</th><th>Jenis</th><th class="r">Qty</th><th>Referensi</th><th>User</th></tr></thead><tbody>${[...DB.invTx.map(t=>({date:t.date,item:DB.inventory.find(i=>i.id===t.item).name,type:t.type,qty:t.qty,ref:t.ref,user:t.user,unit:DB.inventory.find(i=>i.id===t.item).unit})),...DB.feedPurchases.filter(p=>p.status==='APPROVED').map(p=>({date:p.date,item:'Pakan',type:'IN',qty:p.qty,ref:p.ref,user:p.user,unit:'kg'})),...DB.feedRecords.slice(-6).map(r=>({date:r.date,item:'Pakan',type:'OUT',qty:calc.feedVal(r),ref:'Pemakaian '+barnName(r.barn),user:r.user,unit:'kg'}))].sort((a,b)=>b.date-a.date).map(t=>`<tr><td class="num">${fmtDT(t.date)}</td><td>${t.item}</td><td>${badge(t.type==='IN'?'ok':'danger',t.type==='IN'?'MASUK':'KELUAR')}</td><td class="r num" style="color:${t.type==='IN'?'var(--soft)':'#F29390'}">${t.type==='IN'?'+':'−'}${num(t.qty)} ${t.unit}</td><td>${t.ref}</td><td>${userName(t.user)}</td></tr>`).join('')}</tbody></table></div></div>`:
 `<div class="card"><div class="card-h"><h3>Hasil Opname</h3><span class="sub">Selisih ≥ 10 kg otomatis ditandai Perlu Verifikasi</span></div><div class="tbl-wrap"><table><thead><tr><th>Tanggal</th><th>Item</th><th class="r">Teoritis</th><th class="r">Fisik</th><th class="r">Selisih</th><th>User</th><th>Status</th><th></th></tr></thead><tbody>${DB.feedOpname.map(o=>{const t=calc.feedStockAtDate(o.date);const dif=t-o.physical;return `<tr><td class="num">${fmtDT(o.date)}</td><td>Pakan</td><td class="r num">${num(t)} kg</td><td class="r num">${num(o.physical)} kg</td><td class="r num"><b style="color:${Math.abs(dif)>=10?'#F2C46B':'var(--soft)'}">${num(dif)} kg</b></td><td>${userName(o.user)}</td><td>${Math.abs(dif)>=10?stBadge('OPEN'):stBadge('VERIFIED')}</td><td>${Math.abs(dif)>=10&&can('approve')?`<button class="btn sm" data-act="modal" data-m="adjust">Ajukan penyesuaian</button>`:''}</td></tr>`;}).join('')}</tbody></table></div></div>`}`;}

function pgLaporan(){const f=state.filters;const kinds=['Laporan Harian','Laporan Mingguan','Laporan Siklus','Laporan Keuangan','Laporan Pakan','Laporan Mortalitas','Laporan Pertumbuhan','Laporan Penjualan'].filter(k=>can('finance')||!k.includes('Keuangan'));const sel=f.rep||'Laporan Harian';
 const rows=(()=>{if(sel==='Laporan Harian'){const d=f.day||calc.day();const end=new Date(dateOfDay(d).getTime()+86399000);return{cols:['Metrik','Nilai'],rows:[['Tanggal',fmtLong(dateOfDay(d))+' (H'+d+')'],['Populasi akhir hari',num(calc.population(null,end))+' ekor'],['Kematian',calc.mortByDay()[d-1]+' ekor'],['Pakan',calc.feedByDay()[d-1]+' kg'],['Bobot (sampel terakhir)',(calc.weightSeries().filter(w=>w.day<=d).slice(-1)[0]||{avg:0}).avg.toFixed(2)+' kg'],['Stok pakan',num(calc.feedStockAtDate(end))+' kg'],['Input oleh',[...new Set(DB.feedRecords.filter(r=>dayOf(r.date)===d).map(r=>userName(r.user)))].join(', ')||'—']]};}
  if(sel==='Laporan Mortalitas'){const list=DB.mortality.filter(m=>(!f.barn||f.barn==='ALL'||m.barn===f.barn));return{cols:['Tanggal','Kandang','Jumlah','Penyebab','User'],rows:list.map(m=>[fmtDate(m.date),barnName(m.barn),m.qty,m.cause,userName(m.user)])};}
  if(sel==='Laporan Pakan'){return{cols:['Hari','Tanggal','Kandang A','Kandang B','Total','Rata-rata 7 hari'],rows:[...Array(calc.day()).keys()].map(i=>i+1).filter(d=>!f.barn||f.barn==='ALL'||true).slice(-14).map(d=>{const a=DB.feedRecords.filter(r=>dayOf(r.date)===d&&r.barn==='A').reduce((s,r)=>s+calc.feedVal(r),0),b=DB.feedRecords.filter(r=>dayOf(r.date)===d&&r.barn==='B').reduce((s,r)=>s+calc.feedVal(r),0);const fb=calc.feedByDay();const s=fb.slice(Math.max(0,d-7),d);return['H'+d,fmtDate(dateOfDay(d)),a+' kg',b+' kg',(a+b)+' kg',num(s.reduce((x,y)=>x+y,0)/s.length,1)+' kg'];})};}
  if(sel==='Laporan Pertumbuhan'){return{cols:['Hari','Tanggal','Kandang','Sampel','Rata-rata','Target','Gap'],rows:DB.weights.filter(w=>!f.barn||f.barn==='ALL'||w.barn===f.barn).map(w=>{const d=dayOf(w.date);const t=calc.target(d);return['H'+d,fmtDate(w.date),barnName(w.barn),w.n,num(w.avg,2)+' kg',num(t,2)+' kg',((w.avg-t)/t*100).toFixed(1)+'%'];})};}
  if(sel==='Laporan Penjualan'){return{cols:['Order','Tanggal','Customer','Produk','Qty','Total','Status'],rows:DB.orders.map(o=>[o.id,fmtDate(o.date),DB.customers.find(c=>c.id===o.customer).name,DB.products.find(p=>p.id===o.product).name,o.qty,can('finance')?rp(calc.orderTotal(o)):'—',o.status])};}
  if(sel==='Laporan Keuangan'){const c=calc.costByCat();return{cols:['Kategori','Nominal','%'],rows:[...Object.entries(c).map(([k,v])=>[k,rp(v),pct(v/calc.modal()*100)]),['TOTAL',rp(calc.modal()),'100%'],['Estimasi omzet',rp(calc.estRevenue()),''],['Estimasi laba',rp(calc.estProfit()),'ROI '+pct(calc.roi())]]};}
  if(sel==='Laporan Mingguan'){return{cols:['Minggu','Populasi akhir','Mati','Pakan','Bobot','FCR'],rows:[1,2,3,4,5].map(w=>{const d=Math.min(calc.day(),w*7);const end=new Date(dateOfDay(d).getTime()+86399000);const mb=calc.mortByDay().slice((w-1)*7,w*7).reduce((a,b)=>a+b,0);const fb=calc.feedByDay().slice((w-1)*7,w*7).reduce((a,b)=>a+b,0);const ws=calc.weightSeries().find(x=>x.day===w*7)||(w===5?calc.weightSeries().slice(-1)[0]:null);const fs=calc.fcrSeries().find(x=>x.day===(ws?ws.day:0));return['Mgg '+w,num(calc.population(null,end)),mb,fb+' kg',ws?num(ws.avg,2)+' kg':'—',fs&&fs.fcr?num(fs.fcr,2):'—'];})};}
  return{cols:['Ringkasan','Nilai'],rows:[['Siklus',DB.cycle.code],['DOD',DB.cycle.dodQty],['Hari berjalan',calc.day()],['Populasi',num(calc.population())],['Mortalitas',pct(calc.mortPct())],['Pakan kumulatif',num(calc.feedTotal())+' kg'],['Bobot rata-rata',num(calc.avgWeight(),2)+' kg'],['FCR',calc.fcr()?num(calc.fcr().fcr,2):'—'],...(can('finance')?[['Modal berjalan',rp(calc.modal())],['Estimasi laba',rp(calc.estProfit())]]:[])]};})();
 return pageHead('Laporan','Laporan dihasilkan dari data transaksi yang sama dengan dashboard. Export PDF, Excel, atau CSV.',`<button class="btn" data-act="export" data-what="${sel}" data-fmt="PDF">${ic('dl',14)} PDF</button><button class="btn" data-act="export" data-what="${sel}" data-fmt="Excel">${ic('dl',14)} Excel</button><button class="btn" data-act="export" data-what="${sel}" data-fmt="CSV">${ic('dl',14)} CSV</button>`)+
 `<div class="grid" style="grid-template-columns:240px 1fr"><div class="card flat"><div class="nav">${kinds.map(k=>`<button class="${sel===k?'active':''}" data-act="rep" data-v="${k}">${ic('report')}<span>${k}</span></button>`).join('')}</div></div>
 <div class="card"><div class="card-h"><h3>${sel}</h3><div class="row"><div class="f" style="flex-direction:row;align-items:center;gap:6px"><label>Kandang</label><select data-act="repbarn" style="padding:6px 10px"><option value="ALL">Semua</option><option value="A" ${f.barn==='A'?'selected':''}>Kandang A</option><option value="B" ${f.barn==='B'?'selected':''}>Kandang B</option></select></div>${sel==='Laporan Harian'?`<div class="f" style="flex-direction:row;align-items:center;gap:6px"><label>Hari</label><select data-act="repday" style="padding:6px 10px">${[...Array(calc.day()).keys()].map(i=>i+1).reverse().map(d=>`<option value="${d}" ${(f.day||calc.day())===d?'selected':''}>H${d} · ${fmtDate(dateOfDay(d))}</option>`).join('')}</select></div>`:''}<div class="f" style="flex-direction:row;align-items:center;gap:6px"><label>Siklus</label><select style="padding:6px 10px"><option>#001</option><option>#000</option></select></div></div></div>
 ${rows.rows.length?`<div class="tbl-wrap"><table><thead><tr>${rows.cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.rows.map(r=>`<tr>${r.map(c=>`<td class="num" style="white-space:normal">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:emptyState('Tidak ada data untuk filter ini','Ubah filter kandang atau tanggal.')}<p style="color:var(--dim);font-size:11px;margin-top:10px">Dibuat ${fmtDT(DEMO_TODAY)} oleh ${state.user.name} · DEMO DATA</p></div></div>`;}

function pgPersetujuan(){if(!can('approve')&&state.user.role!=='ADMIN')return denied();const list=calc.pendingApprovals();const tab=state.tab||'pending';const done=DB.corrections.filter(c=>c.status!=='PENDING');
 return pageHead('Persetujuan','Koreksi data, pembelian, dan penjualan tertentu membutuhkan persetujuan. Data lama tidak pernah dihapus.',`<span class="badge b-danger">${list.length} menunggu</span>`)+
 `<div class="tabs"><button class="${tab==='pending'?'active':''}" data-act="tab" data-v="pending">Menunggu (${list.length})</button><button class="${tab==='riwayat'?'active':''}" data-act="tab" data-v="riwayat">Riwayat Keputusan</button></div>
 ${tab==='pending'?(list.length?`<div class="grid g-2">${list.map(p=>`<div class="card"><div class="card-h"><div class="row">${badge(p.kind==='CORRECTION'?'gold':'info',p.kind==='CORRECTION'?'KOREKSI DATA':p.kind==='ORDER'?'PENJUALAN':p.kind==='PURCHASE'?'PEMBELIAN':'BIAYA')}${stBadge('PENDING')}</div><span class="sub">${fmtDT(p.date)}</span></div><h3 style="font-size:16px">${p.title}</h3><p style="color:var(--muted);margin:4px 0 12px">${p.sub}</p>
  ${p.kind==='CORRECTION'?`<div class="grid" style="grid-template-columns:1fr 1fr;gap:10px"><div class="barn-card"><small style="color:var(--muted)">Data lama</small><div class="num" style="font-size:22px;font-weight:800"><s style="color:var(--dim)">${p.ref.oldVal} kg</s></div><small style="color:var(--dim)">Record ${p.ref.recordId}</small></div><div class="barn-card" style="border-color:rgba(168,208,141,.4)"><small style="color:var(--muted)">Data baru</small><div class="num" style="font-size:22px;font-weight:800;color:var(--soft)">${p.ref.newVal} kg</div><small style="color:var(--dim)">Bukti ${p.ref.photo} ${photoChip(p.ref.photo)}</small></div></div>`:p.kind==='PURCHASE'?`<div class="kv"><span>Vendor</span><b>${p.ref.vendor}</b><span>Harga</span><b class="num">${rp(p.ref.price)}/kg</b><span>No. bukti</span><b>${p.ref.ref}</b><span>Catatan</span><b>${p.ref.note||'—'}</b><span>Nota</span><b>${photoChip('nota')}</b></div>`:p.kind==='ORDER'?`<div class="kv"><span>Produk</span><b>${DB.products.find(x=>x.id===p.ref.product).name}</b><span>Berat</span><b class="num">${num(p.ref.weight,1)} kg</b><span>Harga</span><b class="num">${rp(p.ref.priceKg)}/kg</b><span>Stok saat ini</span><b class="num">${num(calc.productStock(DB.products.find(x=>x.id===p.ref.product)))} ekor</b></div>`:''}
  <div class="row" style="margin-top:14px;justify-content:space-between"><small style="color:var(--muted)">Diajukan oleh <b>${userName(p.by)}</b> (${userRole(p.by)})</small>${can('approve')?`<div class="row"><button class="btn danger" data-act="reject" data-id="${p.id}" data-kind="${p.kind}">${ic('x',14)} Tolak</button><button class="btn ok" data-act="approve" data-id="${p.id}" data-kind="${p.kind}">${ic('check',14)} Setujui</button></div>`:'<span class="badge b-neutral">Hanya Owner/Manager</span>'}</div></div>`).join('')}</div>`:`<div class="card">${emptyState('Semua sudah diproses','Tidak ada permintaan yang menunggu persetujuan.')}</div>`):
 `<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Waktu</th><th>Jenis</th><th>Detail</th><th>Diajukan</th><th>Diputuskan</th><th>Status</th></tr></thead><tbody>${[...done.map(c=>`<tr><td class="num">${fmtDT(c.decidedAt||c.requestedAt)}</td><td>${badge('gold','KOREKSI')}</td><td>${c.recordId}: ${c.oldVal} kg → ${c.newVal} kg · ${c.reason}${c.rejectReason?' · Alasan tolak: '+c.rejectReason:''}</td><td>${userName(c.requestedBy)}</td><td>${userName(c.decidedBy)}</td><td>${stBadge(c.status)}</td></tr>`),...DB.feedPurchases.filter(p=>p.status!=='PENDING').map(p=>`<tr><td class="num">${fmtDT(p.date)}</td><td>${badge('info','PEMBELIAN')}</td><td>Pakan ${num(p.qty)} kg · ${rp(p.qty*p.price)}</td><td>${userName(p.user)}</td><td>${userName('U1')}</td><td>${stBadge(p.status)}</td></tr>`),...DB.orders.filter(o=>o.decidedBy).map(o=>`<tr><td class="num">${fmtDT(o.decidedAt)}</td><td>${badge('info','PENJUALAN')}</td><td>${o.id} · ${o.qty} ekor</td><td>${userName(o.user)}</td><td>${userName(o.decidedBy)}</td><td>${stBadge(o.status==='CANCELLED'?'REJECTED':'APPROVED')}</td></tr>`)].join('')||'<tr><td colspan="6">'+emptyState('Belum ada riwayat','')+'</td></tr>'}</tbody></table></div></div>`}`;}

function pgPengguna(){if(!can('manageUsers'))return denied();
 return pageHead('Pengguna','Kelola akun, role, dan kandang. Password tidak pernah ditampilkan; reset hanya lewat tautan sekali pakai.',`<button class="btn primary" data-act="modal" data-m="user">${ic('plus',14)} Tambah Pengguna</button>`)+
 `<div class="card"><div class="tbl-wrap"><table><thead><tr><th>Nama</th><th>Role</th><th>Kandang</th><th>Kontak</th><th>Login terakhir</th><th>Status</th><th>Password</th><th></th></tr></thead><tbody>${DB.users.map(u=>`<tr><td><div class="row" style="gap:8px"><span class="avatar">${u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><b>${u.name}</b></div></td><td>${badge(u.role==='OWNER'?'gold':u.role==='MANAGER'?'ok':u.role==='ADMIN'?'info':'neutral',ROLES[u.role].label.toUpperCase())}</td><td>${u.barn?barnName(u.barn):'Semua'}</td><td class="num">${u.phone}</td><td class="num">${fmtDT(u.lastLogin)}</td><td>${u.active?badge('ok','AKTIF'):badge('danger','NONAKTIF')}</td><td><span style="color:var(--dim)">••••••••</span> <button class="btn ghost sm" data-act="toast" data-msg="Tautan reset password dikirim ke ${u.phone}">Reset</button></td><td>${u.id!==state.user.id?`<button class="btn sm ${u.active?'danger':'ok'}" data-act="user-toggle" data-id="${u.id}">${u.active?'Nonaktifkan':'Aktifkan'}</button>`:'<span class="badge b-neutral">Anda</span>'}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="card" style="margin-top:14px"><div class="card-h"><h3>Matriks Hak Akses</h3><span class="sub">Divalidasi di backend pada setiap request</span></div><div class="tbl-wrap"><table><thead><tr><th>Kemampuan</th><th>Owner</th><th>Manager</th><th>Admin</th><th>Anak Kandang</th></tr></thead><tbody>${[['Lihat keuangan & laba','✓','—','✓','—'],['Approve koreksi & transaksi','✓','✓ (operasional)','—','—'],['Input pakan / kematian / timbang','✓','✓','—','✓ (kandang sendiri)'],['Input pembelian & penjualan','✓','—','✓','—'],['Master data & konfigurasi','✓','—','✓ (terbatas)','—'],['Kelola pengguna','✓','—','✓','—'],['Lihat audit trail','✓','✓','✓','—'],['Hapus data operasional','— (soft delete + approval)','—','—','—'],['Ubah transaksi terkunci','— (via koreksi)','— (via koreksi)','— (via koreksi)','— (via koreksi)']].map(r=>`<tr>${r.map((c,i)=>`<td ${i?'style="color:'+(c==='—'?'var(--dim)':'var(--soft)')+'"':''}>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}

function pgPengaturan(){if(!can('masterData'))return denied();const tab=state.tab||'master';
 return pageHead('Pengaturan','Master data menentukan semua angka turunan di sistem. Perubahan tercatat di audit trail.')+
 `<div class="tabs">${[['master','Master Data'],['anomali','Aturan Anomali'],['kandang','Kandang'],['ds','Design System & UI States'],['arch','Arsitektur Data']].map(([k,l])=>`<button class="${tab===k?'active':''}" data-act="tab" data-v="${k}">${l}</button>`).join('')}</div>
 ${tab==='master'?`<div class="grid g-2"><div class="card"><div class="card-h"><h3>Harga & Target</h3>${badge('gold','OWNER ONLY')}</div><form class="form" data-act="save-master">${[['hargaDOD','Harga DOD (Rp/ekor)'],['hargaPakanKg','Harga pakan default (Rp/kg)'],['hargaJualHidupKg','Harga jual hidup (Rp/kg)'],['hargaJualPotongKg','Harga jual potong (Rp/kg)'],['hargaJualKarkasKg','Harga jual karkas (Rp/kg)'],['targetPanenHari','Target panen (hari)'],['targetBobotMin','Target bobot minimum (kg)'],['targetBobotMax','Target bobot maksimum (kg)'],['targetMortalitasPct','Target mortalitas maksimum (%)'],['minStokPakanHari','Minimum stok pakan (hari)']].map(([k,l])=>`<div class="f"><label>${l}</label><input name="${k}" type="number" step="any" value="${MASTER[k]}" ${state.user.role!=='OWNER'?'disabled class="ro"':''}></div>`).join('')}${state.user.role==='OWNER'?'<button class="btn primary" type="submit">Simpan perubahan</button>':'<div class="alert info">Hanya Owner yang dapat mengubah harga dan target.</div>'}</form></div>
 <div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="card-h"><h3>Kebijakan Bukti & Keamanan</h3></div><div class="form">${[['Foto bukti wajib untuk input pakan, kematian, timbang',MASTER.fotoWajib],['Lokasi GPS dicatat pada input mobile',true],['Kunci transaksi otomatis setelah 24 jam',true],['Koreksi memerlukan approval Owner/Manager',true],['Rate limit login 5x / 15 menit',true],['Sesi berakhir setelah 12 jam tidak aktif',true]].map(([l,v])=>`<div class="row" style="justify-content:space-between"><span style="font-size:13px">${l}</span>${badge(v?'ok':'neutral',v?'AKTIF':'NONAKTIF')}</div>`).join('')}</div></div>
 <div class="card"><div class="card-h"><h3>Riwayat Perubahan Master Data</h3></div>${DB.audit.filter(a=>a.entity==='MasterData').length?`<div class="timeline">${DB.audit.filter(a=>a.entity==='MasterData').map(a=>`<div class="tl done"><div class="t">${fmtDT(a.date)}</div><div class="b">${a.detail}</div><div class="d">${userName(a.user)}</div></div>`).join('')}</div>`:emptyState('Belum ada perubahan','Perubahan master data akan tercatat di sini dan di audit trail.')}</div></div></div>`:
 tab==='anomali'?`<div class="card"><div class="card-h"><h3>Aturan Deteksi Anomali</h3><span class="sub">Bahasa netral: "Perlu Verifikasi", bukan tuduhan</span></div><div class="tbl-wrap"><table><thead><tr><th>Aturan</th><th>Ambang</th><th>Tingkat</th><th>Status</th></tr></thead><tbody>${[['Konsumsi pakan menyimpang dari rata-rata 7 hari','± '+MASTER.batasPakanPct+'%','WARNING'],['Selisih stok opname vs teoritis','≥ 10 kg','WARNING'],['Kematian harian','≥ '+MASTER.batasMortalitasHarian+' ekor','CRITICAL'],['Bobot tertinggal dari kurva target','< −3%','WARNING'],['FCR naik antar pengukuran','> 5%','WARNING'],['Input berulang per kandang/hari','> 1 input','WARNING'],['Transaksi di luar jam kerja',MASTER.jamKerja[0]+':00–'+MASTER.jamKerja[1]+':00','INFO'],['Perubahan data terlalu sering','> 3 koreksi / user / minggu','WARNING'],['Populasi tidak balance','≠ 0','CRITICAL'],['Stok pakan tersisa','< '+MASTER.minStokPakanHari+' hari','CRITICAL']].map(([r,t,s])=>`<tr><td style="white-space:normal">${r}</td><td class="num">${t}</td><td>${stBadge(s)}</td><td>${badge('ok','AKTIF')}</td></tr>`).join('')}</tbody></table></div></div>`:
 tab==='kandang'?`<div class="grid g-3">${DB.barns.map(b=>`<div class="card"><div class="card-h"><h3>${b.name}</h3>${calc.population(b.id)?badge('ok','TERISI'):badge('neutral','KOSONG')}</div><div class="kv"><span>Kapasitas</span><b class="num">${b.cap} ekor</b><span>Populasi</span><b class="num">${num(calc.population(b.id))} ekor</b><span>PIC</span><b>${DB.users.filter(u=>u.barn===b.id&&u.active).map(u=>u.name).join(', ')||'—'}</b>${b.note?`<span>Catatan</span><b>${b.note}</b>`:''}</div></div>`).join('')}</div>`:
 tab==='ds'?pgDesignSystem():pgArch()}`;}
function pgDesignSystem(){return `<div class="ds-grid">
 <div class="card"><div class="card-h"><h3>Warna</h3></div><div style="display:flex;flex-direction:column;gap:8px">${[['Deep Forest','#174A3A'],['Dark Green','#0F3328'],['Sage','#7FA68C'],['Soft Green','#A8D08D'],['Warm White','#F7F8F5'],['Charcoal','#1F2933'],['Gold','#C6A15B'],['Warning','#D99A2B'],['Danger','#D9534F'],['Success','#2E8B57']].map(([n,h])=>`<div class="swatch"><i style="background:${h}"></i><b>${n}</b><code style="color:var(--muted)">${h}</code></div>`).join('')}</div></div>
 <div class="card"><div class="card-h"><h3>Badge & Status</h3></div><div class="chips">${['APPROVED','PENDING','REJECTED','RECORDED','LOCKED','NEW','CONFIRMED','PAID','DELIVERED','CANCELLED','OPEN','VERIFIED','NORMAL','WARNING','CRITICAL'].map(stBadge).join(' ')}</div><div class="card-h" style="margin-top:16px"><h3>Button</h3></div><div class="chips"><button class="btn primary">Primary</button><button class="btn">Default</button><button class="btn gold">Gold</button><button class="btn ok">Setujui</button><button class="btn danger">Tolak</button><button class="btn ghost">Ghost</button><button class="btn" disabled>Disabled</button></div></div>
 <div class="card"><div class="card-h"><h3>Alert</h3></div><div style="display:flex;flex-direction:column;gap:8px"><div class="alert ok">${ic('check',16)}<div><b>Success</b>Data berhasil dicatat.</div></div><div class="alert warn">${ic('alert',16)}<div><b>Warning</b>Selisih stok perlu verifikasi.</div></div><div class="alert danger">${ic('alert',16)}<div><b>Critical</b>Mortalitas di atas batas.</div></div><div class="alert info">${ic('lock',16)}<div><b>Pending</b>Menunggu persetujuan.</div></div></div></div>
 <div class="card"><div class="card-h"><h3>Loading Skeleton</h3></div>${skeleton()}</div>
 <div class="card"><div class="card-h"><h3>Empty State</h3></div>${emptyState('Belum ada data','Data akan tampil setelah input pertama.','<button class="btn primary sm">Tambah data</button>')}</div>
 <div class="card"><div class="card-h"><h3>Error State</h3></div><div class="empty">${ic('alert',30)}<b>Gagal memuat data</b><span>Koneksi ke server terputus. Coba lagi.</span><button class="btn sm" data-act="toast" data-msg="Mencoba memuat ulang…" data-k="warn">Coba lagi</button></div></div>
 <div class="card"><div class="card-h"><h3>Permission Denied</h3></div><div class="denied" style="padding:20px"><div class="lock">${ic('lock',24)}</div><b>Akses ditolak</b><small style="color:var(--muted)">Role tidak memiliki izin.</small></div></div>
 <div class="card"><div class="card-h"><h3>Toast</h3></div><div class="chips"><button class="btn sm" data-act="toast" data-msg="Data berhasil dicatat." data-k="ok">Success toast</button><button class="btn sm" data-act="toast" data-msg="Terjadi kesalahan." data-k="err">Error toast</button><button class="btn sm" data-act="toast" data-msg="Perlu verifikasi." data-k="warn">Warning toast</button></div><div class="card-h" style="margin-top:16px"><h3>Audit Timeline</h3></div><div class="timeline"><div class="tl done"><div class="t">26 SEP 18:42</div><div class="b">CREATE · Input pakan 85 kg</div><div class="d">Budi (Anak Kandang) · Bukti Foto #123</div></div><div class="tl now"><div class="t">26 SEP 19:10</div><div class="b">CORRECTION · 85 kg → 80 kg</div><div class="d">Alasan: salah input · menunggu approval</div></div></div></div>
 <div class="card"><div class="card-h"><h3>Typography</h3></div><div style="display:flex;flex-direction:column;gap:6px"><span style="font-family:Fraunces,serif;font-size:30px">Display · Fraunces</span><span style="font-size:26px;font-weight:800" class="num">KPI 1.250 kg</span><span style="font-size:15px;font-weight:700">Heading · Plus Jakarta Sans</span><span>Body 14px · mudah dibaca di mobile</span><span style="font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--dim);font-weight:700">Label uppercase</span></div></div></div>`;}
function pgArch(){return `<div class="grid g-2"><div class="card"><div class="card-h"><h3>Entity Relationship</h3><span class="sub">Rancangan minimal</span></div><div style="overflow-x:auto;background:var(--warm);border-radius:12px;padding:10px"><pre class="mermaid">erDiagram
  USER ||--o{ AUDIT_LOG : performs
  USER }o--|| ROLE : has
  USER }o--o| BARN : assigned
  FARM ||--o{ BARN : contains
  FARM ||--o{ CYCLE : runs
  CYCLE ||--o{ ANIMAL_POPULATION_TX : ledger
  CYCLE ||--o{ MORTALITY : records
  CYCLE ||--o{ FEED_TRANSACTION : uses
  CYCLE ||--o{ WEIGHT_RECORD : samples
  CYCLE ||--o{ HEALTH_RECORD : treats
  CYCLE ||--o{ EXPENSE : costs
  BARN ||--o{ MORTALITY : in
  BARN ||--o{ FEED_TRANSACTION : in
  BARN ||--o{ WEIGHT_RECORD : in
  FEED ||--o{ FEED_TRANSACTION : item
  FEED ||--|| FEED_STOCK : derived
  PURCHASE ||--o{ FEED_TRANSACTION : IN
  PURCHASE ||--o{ INVENTORY_TRANSACTION : IN
  INVENTORY ||--o{ INVENTORY_TRANSACTION : ledger
  PRODUCT ||--o{ ORDER_ITEM : sold
  CUSTOMER ||--o{ ORDER : places
  ORDER ||--|{ ORDER_ITEM : contains
  ORDER ||--o| SALE : settles
  ORDER_ITEM ||--o{ INVENTORY_TRANSACTION : OUT
  ORDER_ITEM ||--o{ ANIMAL_POPULATION_TX : PENJUALAN
  CORRECTION_REQUEST ||--|| APPROVAL : needs
  PURCHASE ||--o| APPROVAL : needs
  EXPENSE ||--o| APPROVAL : needs
  ATTACHMENT }o--|| USER : uploaded_by
  ANOMALY }o--|| CYCLE : detected_in
  ANOMALY ||--o{ NOTIFICATION : triggers
  APPROVAL ||--o{ NOTIFICATION : triggers</pre></div></div>
 <div style="display:flex;flex-direction:column;gap:14px"><div class="card"><div class="card-h"><h3>Prinsip Integritas Data</h3></div><div class="timeline">${[['Ledger, bukan saldo','Populasi dan stok tidak disimpan sebagai angka yang bisa diedit. Keduanya dihitung dari tabel transaksi (append-only).'],['Immutable event log','AuditLog hanya INSERT. Tidak ada UPDATE/DELETE di level database (revoke privilege).'],['Versi, bukan overwrite','Koreksi membuat versi baru pada record; versi lama tetap ada dengan status SUPERSEDED.'],['Approval sebagai state machine','PENDING → APPROVED/REJECTED. Transisi hanya oleh role yang berhak, dicatat siapa & kapan.'],['Soft delete','Field deleted_at + deleted_by + reason. Data tidak pernah hilang secara fisik.'],['Bukti terkunci','Attachment mendapat hash SHA-256 saat upload; penggantian membuat attachment baru berversi.'],['Validasi server','Semua permission, validasi input, rate limiting dan sesi diperiksa di backend. UI hanya cerminan.']].map(([b,d])=>`<div class="tl done"><div class="b">${b}</div><div class="d">${d}</div></div>`).join('')}</div></div>
 <div class="card"><div class="card-h"><h3>Aksi Audit</h3></div><div class="chips">${['CREATE','UPDATE','DELETE_REQUEST','APPROVE','REJECT','LOGIN','LOGOUT','UPLOAD','CORRECTION','STOCK_ADJUSTMENT','STOCK_OPNAME','APPROVAL'].map(a=>`<span class="chip">${a}</span>`).join('')}</div></div></div></div>`;}

function pgAudit(){const f=state.filters;const list=DB.audit.filter(a=>(!f.au||f.au==='ALL'||a.user===f.au)&&(!f.aa||f.aa==='ALL'||a.action===f.aa)&&(!f.q||a.detail.toLowerCase().includes(f.q.toLowerCase())));
 return pageHead('Audit Trail','Log immutable. Setiap aksi tercatat: siapa, kapan, apa, dan buktinya. Tidak ada tombol hapus.',`<span class="badge b-neutral">${ic('lock',12)} APPEND-ONLY</span><button class="btn" data-act="export" data-what="Audit Log" data-fmt="CSV">${ic('dl',14)} Export CSV</button>`)+
 `<div class="card"><div class="card-h"><div class="row"><select data-act="audit-user" style="padding:6px 10px;background:rgba(255,255,255,.06);border:1px solid var(--line2);border-radius:8px;color:var(--text)"><option value="ALL">Semua user</option>${DB.users.map(u=>`<option value="${u.id}" ${f.au===u.id?'selected':''}>${u.name}</option>`).join('')}<option value="SYSTEM" ${f.au==='SYSTEM'?'selected':''}>Sistem</option></select><select data-act="audit-action" style="padding:6px 10px;background:rgba(255,255,255,.06);border:1px solid var(--line2);border-radius:8px;color:var(--text)"><option value="ALL">Semua aksi</option>${['CREATE','CORRECTION','APPROVE','REJECT','LOGIN','LOGOUT','STOCK_OPNAME','STOCK_ADJUSTMENT','UPDATE','UPLOAD'].map(a=>`<option ${f.aa===a?'selected':''}>${a}</option>`).join('')}</select><div class="search" style="padding:5px 10px"><input placeholder="Cari detail…" value="${esc(f.q||'')}" data-act="audit-q"></div></div><span class="sub">${list.length} entri</span></div>
 ${list.length?`<div class="timeline">${list.slice(0,40).map(a=>`<div class="tl ${a.action==='APPROVE'?'done':a.action==='CORRECTION'||a.action==='REJECT'?'now':'done'}"><div class="t">${fmtDT(a.date)} · ${badge(a.action==='APPROVE'?'ok':a.action==='REJECT'?'danger':a.action==='CORRECTION'?'gold':a.action==='LOGIN'||a.action==='LOGOUT'?'neutral':'info',a.action)} <span class="badge b-neutral">${a.entity}</span></div><div class="b">${a.detail}</div><div class="d">${userName(a.user)}${userRole(a.user)?' · '+ROLES[userRole(a.user)].label:''} · ref <code style="font-size:11px">${a.ref}</code> · hash <code style="font-size:11px;color:var(--dim)">${a.hash||'—'}</code></div></div>`).join('')}</div>`:emptyState('Tidak ada entri','Ubah filter user, aksi, atau kata kunci.')}</div>`;}

function pgAnomali(){const list=calc.anomalies();const open=list.filter(a=>a.state.status==='OPEN');
 return pageHead('Deteksi Anomali','Engine membandingkan setiap input dengan pola historis. Temuan berstatus "Perlu Verifikasi" — bukan tuduhan.',`<span class="badge b-warn">${open.length} perlu verifikasi</span>`)+
 `<div class="grid g-kpi" style="margin-bottom:14px">${kpi('Perlu Verifikasi',open.length,'temuan','Hari ini','warn','alert')}${kpi('Terverifikasi',list.length-open.length,'temuan','Siklus ini','up','check')}${kpi('Aturan Aktif','10','aturan','Lihat Pengaturan','','shield')}${kpi('Skor Integritas Input','96','/ 100','Berdasarkan bukti & ketepatan waktu','up','shield')}</div>
 ${list.length?`<div class="grid g-2">${list.map(a=>`<div class="card" style="border-color:${a.state.status==='OPEN'?(a.sev==='danger'?'rgba(217,83,79,.4)':a.sev==='warn'?'rgba(217,154,43,.4)':'var(--line)'):'var(--line)'}"><div class="card-h"><div class="row">${stBadge(a.sev==='danger'?'CRITICAL':a.sev==='warn'?'WARNING':'NORMAL')}${stBadge(a.state.status)}</div><span class="sub">${fmtDT(a.date)}</span></div><h3 style="font-size:15px">${a.title}</h3><p style="color:var(--muted);margin:6px 0 10px;font-size:13px">${a.detail}</p><small style="color:var(--dim)">Aturan: ${a.rule}</small>${a.state.note?`<div class="alert ok" style="margin-top:10px">${ic('check',14)}<div><b>Catatan verifikasi</b>${a.state.note} — ${userName(a.state.by)}</div></div>`:''}<div class="row" style="margin-top:12px;justify-content:flex-end"><button class="btn sm" data-act="go" data-page="${a.page}">Lihat data</button>${a.state.status==='OPEN'&&can('approve')?`<button class="btn ok sm" data-act="modal" data-m="verify" data-id="${a.id}">Tandai terverifikasi</button>`:''}</div></div>`).join('')}</div>`:`<div class="card">${emptyState('Tidak ada anomali','Semua parameter dalam batas normal.')}</div>`}`;}
